C SPICE2G.6 -- ENGINE / DYNAMIC MEMORY MANAGER
C Low-level dynamic memory allocator used by the simulation engine
C to manage the shared VALUE() workspace.  Part of the engine layer,
C kept in its own file for clarity.
C
      SUBROUTINE SETMEM(IPNTR,KSIZE)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     THIS ROUTINE PERFORMS DYNAMIC MEMORY MANAGEMENT.  IT IS USED IN
C     SPICE2, AND USEABLE IN ANY PROGRAM.
C
C     MEMORY IS MANAGED WITHIN AN ARRAY SELECTED BY THE CALLING PROGRAM.
C     ONE MAY EITHER DIMENSION THIS ARRAY TO THE 'MAXMEM' SIZE, OR MORE
C     DESIRABLY, FIND THE ADDRESS OF THE FIRST AVAILABLE WORD OF MEMORY
C     ABOVE YOUR PROGRAM, AND DIMENSION YOUR ARRAY TO '1'.  PASSING THE
C     ADDRESS OF THE FIRST DATA WORD AVAILABLE PERMITS THE MANAGER TO
C     USE 'ILLEGAL' INDICES INTO THE DATA AREA.
C
C     THIS ROUTINE MUST HAVE ACCESS TO AN INTEGER FUNCTION CALLED 'LOCF'
C     WHICH RETURNS THE ADDRESS OF ITS ARGUMENT.  ADDRESSES AS USED BY THIS
C     PROGRAM REFER TO 'INTEGER' ADDRESSES, NOT BYTE ADDRESSES.
C
C ENTRY POINTS:
C      SETMEM - SET INITIAL MEMORY
C      GETM4  - GET BLOCK FOR TABLE OF INTEGERS
C      GETM8  - GET BLOCK FOR TABLE OF FLOATING POINT VARIABLES
C      GETM16 - GET BLOCK FOR TABLE OF COMPLEX VARIABLES
C      RELMEM - RELEASE PART OF BLOCK
C      EXTMEM - EXTEND SIZE OF EXISTING BLOCK
C      SIZMEM - DETERMINE SIZE OF EXISTING BLOCK
C      CLRMEM - RELEASE BLOCK
C      PTRMEM - RESET MEMORY POINTER
C      CRUNCH - FORCE MEMORY COMPACTION
C      AVLM4  - AMOUNT OF SPACE AVAILABLE (INTEGERS)
C      AVLM8  - AMOUNT OF SPACE AVAILABLE (REAL)
C      AVLM16 - AMOUNT OF SPACE AVAILABLE (COMPLEX)
C
C CALLING SEQUENCES:
C      CALL SETMEM(IMEM(1),MAXMEM)
C      CALL SETMEM(IMEM(1),MAXMEM,KFAMWA)  CDC MACHINES RUNNING UNDER
C                                          CALIDOSCOPE KFAMWA IS THE ADDRESS
C                                          OF THE FIRST AVAILABLE WORD
C      CALL GETM4 (IPNTR,BLKSIZ)  WHERE BLKSIZE IS THE NUMBER OF ENTRIES
C      CALL GETM8 (IPNTR,BLKSIZ)
C      CALL GETM16(IPNTR,BLKSIZ)
C      CALL RELMEM(IPNTR,RELSIZ)
C      CALL EXTMEM(IPNTR,EXTSIZ)  EXTSIZ IS THE NUMBER OF ENTRIES TO BE ADDED
C      CALL SIZMEM(IPNTR,BLKSIZ)
C      CALL CLRMEM(IPNTR)
C      CALL PTRMEM(IPNTR1,IPNTR2)
C      CALL AVLM4(ISPACE)
C      CALL AVLM8(ISPACE)
C      CALL AVLM16(ISPACE)
C      CALL CRUNCH
C      CALL SLPMEM(IPNTR,SLPSIZ)  EXPRESS DESIRE FOR *SLPSIZ* EXTRA ENTRIES
C
C
C GENERAL COMMENTS:
C      FOR EACH BLOCK WHICH IS ALLOCATED, A MULTI-WORD ENTRY IS MAINTAINED
C IN A TABLE KEPT IN HIGH MEMORY, OF THE FORM
C
C        WORD      CONTENTS
C        ----      --------
C
C          1       INDEX OF IMEM(.) INTO ORIGIN OF BLOCK
C                    I.E. CONTENTS OF POINTER (USED FOR ERROR CHECK)
C          2       BLOCK SIZE (IN WORDS)
C          3       NUMBER OF WORDS IN USE
C          4       ADDRESS OF VARIABLE CONTAINING BLOCK ORIGIN
C          5       NUMBER OF WORDS USED PER TABLE ENTRY
C          6       SLOP SIZE (IN WORDS)
C
C      ALL ALLOCATED BLOCKS ARE AN 'EVEN' (NXTEVN) NUMBER OF WORDS IN LENGTH,
C WHERE A 'WORD' IS THE STORAGE UNIT REQUIRED FOR AN 'INTEGER' VARIABLE.
C      SINCE BLOCK REPOSITIONING MAY BE NECESSARY, THE CONVENTION THAT
C ONLY ONE VARIABLE CONTAIN A BLOCK ORIGIN SHOULD BE OBSERVED.
C      FOR *GETMEM*, *IPNTR* IS SET SUCH THAT *ARRAY(IPNTR+1)* IS THE
C FIRST WORD OF THE ALLOCATED BLOCK.  'IPNTR' IS SET TO ADDRESS THE FIRST
C ENTRY OF THE TABLE WHEN USED WITH THE APPROPRIATE VARIABLE TYPE, I.E.,
C NODPLC(IPNTR+1), VALUE(IPNTR+1), OR CVALUE(IPNTR+1).
C      FOR *CLRMEM*, *IPNTR* IS SET TO 'INVALID' TO ENABLE RAPID DETECTION
C OF AN ATTEMPT TO USE A CLEARED BLOCK.
C      IF ANY FATAL ERRORS ARE FOUND, A MESSAGE IS PRINTED AND A FLAG
C SET INHIBITING FURTHER ACTION UNTIL *SETMEM* IS CALLED.  (IN THIS
C CONTEXT, INSUFFICIENT MEMORY IS CONSIDERED A FATAL ERROR.)
C      THROUGHOUT THIS ROUTINE, *LDVAL* ALWAYS CONTAINS THE SUBSCRIPT OF
C THE LAST ADDRESSABLE WORD OF MEMORY, *MEMAVL* ALWAYS CONTAINS THE
C NUMBER OF AVAILABLE WORDS OF MEMORY, *NUMBLK* ALWAYS CONTAINS THE
C NUMBER OF ALLOCATED BLOCKS, AND ISTACK(*LOCTAB* +1) ALWAYS CONTAINS
C THE FIRST WORD OF THE BLOCK TABLE.
C
C SPICE VERSION 2G.6  SCCSID=BLANK 3/15/83
      COMMON /BLANK/ VALUE(200000)
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      DIMENSION IPNTR(1)
C
      LOGICAL MEMPTR
      COMPLEX CVALUE(32)
      EQUIVALENCE (VALUE(1),CVALUE(1))
C
C...  APPROXIMATE TIME REQUIRED TO COPY *NWORDS* INTEGER VALUES
C
C  NXTEVN ROUNDS THE NUMBER UP TO THE NEXT 'EVEN' VALUE.  THE VALUE
C  USED FOR THIS 'EVEN' NUMBER IS THE SMALLEST NUMBER INTO WHICH ONE
C  CAN DIVIDE NWD4,NWD8,AND NWD16.
C
C
C  NXTMEM  RETURNS NEXT HIGHER MEMORY SIZE
C
C
C
C***  SETMEM - SET INITIAL MEMORY
C
      NWD4=1
      NWD8=LOCF(VALUE(2))-LOCF(VALUE(1))
      NWD16=LOCF(CVALUE(2))-LOCF(CVALUE(1))
      MEMERR=0
      NEVN=NXTEVN(1)
C     CHECK THAT NXTEVN FUNCTION RETURNS A NUMBER DIVISIBLE BY
C     NWD4, NWD8, NWD16; ALSO CHECK THAT THE MEMORY INCREMENT
C     NXTMEM(.) IS AN INTEGER MULTIPLE OF NXTEVN(1)
      ICHECK=MOD(NEVN,NWD4)+MOD(NEVN,NWD8)+MOD(NEVN,NWD16)+
     1  MOD(NXTMEM(1),NEVN)
      IF(ICHECK.EQ.0) GO TO 2
      MEMERR=1
      CALL ERRMEM(6,MEMERR,IPNTR(1))
    2 CPYKNT=0.0D0
      IFAMWA=LOCF(IPNTR(1))
      MAXMEM=KSIZE
      NTAB=NXTEVN(6)
C... ADD 'LORG' TO AN ADDRESS AND YOU GET THE 'ISTACK' INDEX TO THAT WORD
      LORG=1-LOCF(ISTACK(1))
      IFWA=IFAMWA+LORG-1
      NWOFF=LOCF(IPNTR(1))+LORG-1
      ICORE=NXTMEM(1)
C... DON'T TAKE CHANCES, BACK OFF FROM 'END OF MEMORY' BY NXTEVN(1)
      LDVAL=IFWA+NXTMEM(1)-NXTEVN(1)
      MEMAVL=LDVAL-NTAB-IFWA
      MAXCOR=0
      MAXUSE=0
      CALL MEMORY
      IF(MEMERR.NE.0) CALL ERRMEM(6,MEMERR,IPNTR(1))
      NUMBLK=1
      LOCTAB=LDVAL-NTAB
      ISTACK(LOCTAB+1)=0
      ISTACK(LOCTAB+2)=MEMAVL
      ISTACK(LOCTAB+3)=0
      ISTACK(LOCTAB+4)=-1
      ISTACK(LOCTAB+5)=1
      ISTACK(LOCTAB+6)=0
      RETURN
      END
      INTEGER FUNCTION LOCF(IVAR)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C SPICE VERSION 2G.6  SCCSID=STATUS 3/15/83
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
      DIMENSION IVAR(1)
      IABSA=LOC(IVAR)
      LOCF=IABSA/8
      IF (IABSA.EQ.8*LOCF) RETURN
      WRITE(IOFILE,100) IABSA
  100 FORMAT ('0*ERROR*: SYSTEM ERROR, ADDRESS ',I10,
     1   ' IS NOT ON 8-BYTE BOUNDARY')
      RETURN
      END
      SUBROUTINE GETM4(IPNTR,KSIZE)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      DIMENSION IPNTR(1)
      IWSIZE=NWD4
      CALL GETMX(IPNTR(1),KSIZE,IWSIZE)
      RETURN
      END
      SUBROUTINE GETM8(IPNTR,KSIZE)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION IPNTR(1)
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      IWSIZE=NWD8
      CALL GETMX(IPNTR(1),KSIZE,IWSIZE)
      RETURN
      END
      SUBROUTINE GETM16(IPNTR,KSIZE)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION IPNTR(1)
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      IWSIZE=NWD16
      CALL GETMX(IPNTR(1),KSIZE,IWSIZE)
      RETURN
      END
      SUBROUTINE GETMX(IPNTR,KSIZE,IWSIZE)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      LOGICAL MEMPTR
      DIMENSION IPNTR(1)
C
C***  GETMEM - GET BLOCK
C
C
      ISIZE=KSIZE*IWSIZE
C...  CHECK FOR VALID SIZE
      IF (ISIZE.GE.0) GO TO 5
      MEMERR=2
      CALL ERRMEM(3,MEMERR,IPNTR(1))
C...  CHECK FOR ATTEMPT TO REALLOCATE EXISTING BLOCK
    5 IF (.NOT.MEMPTR(IPNTR(1))) GO TO 8
      MEMERR=3
      CALL ERRMEM(3,MEMERR,IPNTR(1))
    8 JSIZE=NXTEVN(ISIZE)
      CALL COMPRS(0,LDVAL)
C...  CHECK IF ENOUGH SPACE ALREADY THERE
      NEED=JSIZE+NTAB-MEMAVL
      IF (NEED.LE.0) GO TO 10
C...  INSUFFICIENT SPACE -- BUMP MEMORY SIZE
      NEED=NXTMEM(NEED)
      ICORE=ICORE+NEED
      CALL MEMORY
      IF(MEMERR.NE.0) CALL ERRMEM(3,MEMERR,IPNTR(1))
      LTAB1=LDVAL-NTAB
      ISTACK(LTAB1+2)=ISTACK(LTAB1+2)+NEED
C...  RELOCATE BLOCK ENTRY TABLE
      NWORDS=NUMBLK*NTAB
      CPYKNT=CPYKNT+DFLOAT(NWORDS)
      CALL COPY4(ISTACK(LOCTAB+1),ISTACK(LOCTAB+NEED+1),NWORDS)
      LOCTAB=LOCTAB+NEED
      LDVAL=LDVAL+NEED
      MEMAVL=MEMAVL+NEED
C...  A BLOCK LARGE ENOUGH NOW EXISTS -- ALLOCATE IT
   10 LTAB1=LDVAL-NTAB
      MORG=ISTACK(LTAB1+1)
      MSIZ=ISTACK(LTAB1+2)
      MUSE=ISTACK(LTAB1+3)
      MUSE=NXTEVN(MUSE)
      MADR=ISTACK(LTAB1+4)
C...  CONSTRUCT NEW TABLE ENTRY
   15 ISTACK(LTAB1+2)=MUSE
      LOCTAB=LOCTAB-NTAB
      NWORDS=NUMBLK*NTAB
      CPYKNT=CPYKNT+DFLOAT(NWORDS)
      CALL COPY4(ISTACK(LOCTAB+NTAB+1),ISTACK(LOCTAB+1),NWORDS)
      NUMBLK=NUMBLK+1
      MEMAVL=MEMAVL-NTAB
      ISTACK(LTAB1+1)=MORG+MUSE
      ISTACK(LTAB1+2)=MSIZ-MUSE-NTAB
C...  SET USER SIZE INTO TABLE ENTRY FOR THIS BLOCK
   20 ISTACK(LTAB1+3)=ISIZE
      ISTACK(LTAB1+4)=LOCF(IPNTR(1))
      ISTACK(LTAB1+5)=IWSIZE
      ISTACK(LTAB1+6)=0
      MEMAVL=MEMAVL-JSIZE
      IPNTR(1)=ISTACK(LTAB1+1)/IWSIZE
      CALL MEMADJ
      RETURN
      END
      SUBROUTINE AVLM4(IAVL)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      IAVL=((MAXMEM-ICORE)/NXTMEM(1))*NXTMEM(1)-NTAB+MEMAVL
      IAVL=IAVL/NWD4
      RETURN
      END
      SUBROUTINE AVLM8(IAVL)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      IAVL=((MAXMEM-ICORE)/NXTMEM(1))*NXTMEM(1)-NTAB+MEMAVL
      IAVL=IAVL/NWD8
      RETURN
      END
      SUBROUTINE AVLM16(IAVL)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      IAVL=((MAXMEM-ICORE)/NXTMEM(1))*NXTMEM(1)-NTAB+MEMAVL
      IAVL=IAVL/NWD16
      RETURN
      END
      SUBROUTINE RELMEM(IPNTR,KSIZE)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION IPNTR(1)
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      LOGICAL MEMPTR
C
C***  RELMEM - RELEASE PART OF BLOCK
C
C
C...  CHECK FOR VALID POINTER
      IF (MEMPTR(IPNTR(1))) GO TO 10
      MEMERR=5
      CALL ERRMEM(5,MEMERR,IPNTR(1))
   10 ISIZE=KSIZE*ISTACK(LTAB+5)
C...  CHECK FOR VALID SIZE
      IF (ISIZE.GE.0) GO TO 20
      MEMERR=2
      CALL ERRMEM(5,MEMERR,IPNTR(1))
   20 JSIZE=ISTACK(LTAB+3)
      IF (ISIZE.LE.JSIZE) GO TO 30
      MEMERR=6
      CALL ERRMEM(5,MEMERR,IPNTR(1))
   30 ISTACK(LTAB+3)=ISTACK(LTAB+3)-ISIZE
      MEMAVL=MEMAVL+(NXTEVN(JSIZE)-NXTEVN(ISTACK(LTAB+3)))
      CALL MEMADJ
      RETURN
      END
      SUBROUTINE EXTMEM(IPNTR,KSIZE)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION IPNTR(1)
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      LOGICAL MEMPTR
C
C***  EXTMEM - EXTEND SIZE OF EXISTING BLOCK
C
C
C...  CHECK FOR VALID POINTER
      IF (MEMPTR(IPNTR(1))) GO TO 10
      MEMERR=5
      CALL ERRMEM(2,MEMERR,IPNTR(1))
   10 ISIZE=KSIZE*ISTACK(LTAB+5)
C...  CHECK FOR VALID SIZE
      IF (ISIZE.GE.0) GO TO 20
      MEMERR=2
      CALL ERRMEM(2,MEMERR,IPNTR(1))
C...  CHECK IF ENOUGH SPACE ALREADY THERE
   20 IF ((ISTACK(LTAB+2)-ISTACK(LTAB+3)).GE.ISIZE) GO TO 40
      NEED=NXTEVN(ISIZE)-MEMAVL
      IF (NEED.LE.0) GO TO 30
C...  INSUFFICIENT SPACE -- BUMP MEMORY SIZE
      NEED=NXTMEM(NEED)
      ICORE=ICORE+NEED
      CALL MEMORY
      IF(MEMERR.NE.0) CALL ERRMEM(2,MEMERR,IPNTR(1))
      LTAB1=LDVAL-NTAB
      ISTACK(LTAB1+2)=ISTACK(LTAB1+2)+NEED
C...  RELOCATE BLOCK ENTRY TABLE
      NWORDS=NUMBLK*NTAB
      CPYKNT=CPYKNT+DFLOAT(NWORDS)
      CALL COPY4(ISTACK(LOCTAB+1),ISTACK(LOCTAB+NEED+1),NWORDS)
      LOCTAB=LOCTAB+NEED
      LDVAL=LDVAL+NEED
      MEMAVL=MEMAVL+NEED
      LTAB=LTAB+NEED
C...  MOVE BLOCKS TO MAKE SPACE
   30 CONTINUE
      CALL COMPRS(0,LTAB)
      CALL COMPRS(1,LTAB)
   40 JSIZE=ISTACK(LTAB+3)
      ISTACK(LTAB+3)=ISTACK(LTAB+3)+ISIZE
      MEMAVL=MEMAVL-(NXTEVN(ISTACK(LTAB+3))-NXTEVN(JSIZE))
      CALL MEMADJ
      RETURN
      END
      SUBROUTINE SIZMEM(IPNTR,KSIZE)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION IPNTR(1)
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      LOGICAL MEMPTR
C
C***  SIZMEM - DETERMINE SIZE OF EXISTING BLOCK
C
C
C...  CHECK FOR VALID POINTER
      IF (MEMPTR(IPNTR(1))) GO TO 10
      MEMERR=5
      CALL ERRMEM(7,MEMERR,IPNTR(1))
   10 KSIZE=ISTACK(LTAB+3)/ISTACK(LTAB+5)
      RETURN
      END
      SUBROUTINE CLRMEM(IPNTR)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION IPNTR(1)
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      LOGICAL MEMPTR
C
C***  CLRMEM - RELEASE BLOCK
C
C
C...  CHECK THAT POINTER IS VALID
      IF (MEMPTR(IPNTR(1))) GO TO 10
      MEMERR=5
      CALL ERRMEM(1,MEMERR,IPNTR(1))
   10 MSIZ=ISTACK(LTAB+2)
      MUSE=ISTACK(LTAB+3)
      MEMAVL=MEMAVL+NXTEVN(MUSE)+ISTACK(LTAB+6)
C...  ASSUMPTION:  FIRST ALLOCATED BLOCK IS NEVER CLEARED.
      LTAB1=LTAB-NTAB
      ISTACK(LTAB1+2)=ISTACK(LTAB1+2)+MSIZ
C...  REPOSITION THE BLOCK TABLE
      NWORDS=LTAB-LOCTAB
      CPYKNT=CPYKNT+DFLOAT(NWORDS)
      CALL COPY4(ISTACK(LOCTAB+1),ISTACK(LOCTAB+NTAB+1),NWORDS)
      NUMBLK=NUMBLK-1
      LOCTAB=LOCTAB+NTAB
      MEMAVL=MEMAVL+NTAB
      LTAB1=LDVAL-NTAB
      ISTACK(LTAB1+2)=ISTACK(LTAB1+2)+NTAB
      IPNTR(1)=2**30-1
      CALL MEMADJ
      RETURN
      END
      SUBROUTINE PTRMEM(IPNTR,IPNTR2)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION IPNTR(1),IPNTR2(1)
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      LOGICAL MEMPTR
C
C***  PTRMEM - RESET MEMORY POINTER
C
C...  VERIFY THAT POINTER IS VALID
      IF (MEMPTR(IPNTR(1))) GO TO 10
      MEMERR=5
      CALL ERRMEM(4,MEMERR,IPNTR(1))
C...  RESET BLOCK POINTER TO BE *IPNTR2*
   10 IPNTR2(1)=IPNTR(1)
      ISTACK(LTAB+4)=LOCF(IPNTR2(1))
      CALL MEMADJ
      RETURN
      END
      SUBROUTINE CRUNCH
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      CALL COMPRS(0,LDVAL)
      CALL MEMADJ
      RETURN
      END
      SUBROUTINE ERRMEM(INAM,IERROR,IPNTR)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION IPNTR(1)
C SPICE VERSION 2G.6  SCCSID=STATUS 3/15/83
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      DIMENSION ERRNAM(7)
      DATA ERRNAM /6HCLRMEM,6HEXTMEM,6HGETMEM,6HPTRMEM,6HRELMEM,
     1   6HSETMEM,6HSIZMEM/
C
      GO TO (200,410,420,300,510,530),IERROR
C
C*** ERROR(S) FOUND ***
C
C.. NXTEVN AND/OR NXTMEM INCOMPATIBLE WITH NWD4, NWD8, AND NWD16
C
  200 WRITE(IOFILE,201)
  201 FORMAT('0MEMORY MANAGER VARIABLES NWD4-8-16 INCOMPATIBLE WITH NXTE
     1VN AND NXTMEM')
      GO TO 900
C
C...  MEMORY NEEDS EXCEED MAXIMUM AVAILABLE SPACE
  300 WRITE (IOFILE,301) MAXMEM,MAXMEM
  301 FORMAT('0*ERROR*:  MEMORY REQUIREMENT EXCEEDS MACHINE CAPACITY',
     1 /'0 MEMORY NEEDS EXCEED',I6,'(',O6,'B)'/)
      GO TO 900
C...    *ISIZE* < 0
  410 WRITE(IOFILE,411)
  411 FORMAT('0SIZE PARAMETER NEGATIVE')
      GO TO 900
C...  GETMEM:  ATTEMPT TO REALLOCATE EXISTING BLOCK
  420 WRITE(IOFILE,421)
  421 FORMAT('0ATTEMPT TO REALLOCATE EXISTING TABLE')
      GO TO 900
C...    *IPNTR* INVALID
  510 WRITE(IOFILE,511)
  511 FORMAT('0TABLE POINTER INVALID')
      GO TO 900
C...  RELMEM:  *ISIZE* LARGER THAN INDICATED BLOCK
  530 WRITE(IOFILE,531)
  531 FORMAT('0ATTEMPT TO RELEASE MORE THAN TOTAL TABLE')
C...  ISSUE ERROR MESSAGE
  900 WRITE (IOFILE,901) ERRNAM(INAM)
  901 FORMAT('0*ABORT*:  INTERNAL MEMORY MANAGER ERROR AT ENTRY ',
     1  A7)
  950 CALL DMPMEM(IPNTR(1))
 1000 STOP
      END
      SUBROUTINE MEMADJ
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
   50 MAXUSE=MAX0(MAXUSE,(LDVAL-MEMAVL-IFWA))
      MEMDEC=2*NXTMEM(1)
      IF (MEMAVL.LT.MEMDEC) RETURN
C...  COMPRESS CURRENT ALLOCATIONS OF MEMORY
      CALL COMPRS(0,LDVAL)
C...  ADJUST MEMORY SIZE
      MEMDEL=0
   60 ICORE=ICORE-MEMDEC
      MEMDEL=MEMDEL+MEMDEC
      MEMAVL=MEMAVL-MEMDEC
      IF (MEMAVL.GE.MEMDEC) GO TO 60
      LTAB1=LDVAL-NTAB
      ISTACK(LTAB1+2)=ISTACK(LTAB1+2)-MEMDEL
C...  RELOCATE BLOCK ENTRY TABLE
      NWORDS=NUMBLK*NTAB
      CPYKNT=CPYKNT+DFLOAT(NWORDS)
      CALL COPY4(ISTACK(LOCTAB+1),ISTACK(LOCTAB-MEMDEL+1),NWORDS)
      LOCTAB=LOCTAB-MEMDEL
      LDVAL=LDVAL-MEMDEL
      CALL MEMORY
      RETURN
      END
      SUBROUTINE SLPMEM(IPNTR,KSIZE)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C      THIS ROUTINE MAY BE USED TO DEFINE A CERTAIN AMOUNT OF `SLOP' TO
C BE ASSOCIATED WITH A PARTICULAR TABLE MANAGED BY THE MEMORY MANAGER.
C THIS *SLOP* IS DEFINED AS A NUMBER OF ENTRIES IN THE TABLE FOR WHICH
C SPACE IS TO BE HELD ***IF POSSIBLE*** DURING COMPACTION OF THE MANAGED
C AREA OF MEMORY.  THIS FEATURE CAN ELIMINATE THE OVERHEAD INCURRED BY
C ALTERNATIVELY EXTENDING MORE THAN ONE TABLE AT A TIME.  (FOR EXAMPLE,
C IF THE PROGRAM CONTAINS A CODE SEQUENCE
C
C                  DO 100 I=1,500
C                     ...
C                  CALL EXTMEM(TABLE1,1)
C                     ...
C                  CALL EXTMEM(TABLE2,1)
C                     ...
C              100 CONTINUE
C
C THEN THE OVERHEAD INCURRED BY THIS MEMORY MANAGER CAN BE REDUCED TO
C ESSENTIALLY NOTHING IF PRIOR TO THE ABOVE CODE SEQUENCE THE PROGRAM
C EXECUTES
C
C                  CALL SLPMEM(TABLE1,20)
C                  CALL SLPMEM(TABLE2,20)
C
C WHERE `20' IS A TYPICAL NUMBER (FOR THE ABOVE EXAMPLE, THE MEMORY-TO-
C MEMORY COPYING OVERHEAD OF THE MEMORY MANAGER WOULD BE REDUCED BY A
C FACTOR OF 20).
C
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
C SPICE VERSION 2G.6  SCCSID=FLAGS 3/15/83
      COMMON /FLAGS/ IPRNTA,IPRNTL,IPRNTM,IPRNTN,IPRNTO,LIMTIM,LIMPTS,
     1   LVLCOD,LVLTIM,ITL1,ITL2,ITL3,ITL4,ITL5,ITL6,IGOOF,NOGO,KEOF
      DIMENSION IPNTR(1)
      ISLP=NXTEVN(KSIZE)
      CALL EXTMEM(IPNTR,ISLP)
      ISLP=ISLP*ISTACK(LTAB+5)
      ISTACK(LTAB+3)=ISTACK(LTAB+3)-ISLP
      MEMAVL=MEMAVL+ISTACK(LTAB+6)
      ISTACK(LTAB+6)=ISLP
      RETURN
      END
      INTEGER FUNCTION NXTEVN(N)
C
C.. FUNCTION RETURNS THE SMALLEST VALUE NXTEVN GREATER THAN OR EQUAL TO
C.. N WHICH IS EVENLY DIVISIBLE BY 'NWD4, NWD8, AND NWD16' AS DEFINED
C.. IN SETMEM
C
      NXTEVN=((N+3)/4)*4
      RETURN
      END
      INTEGER FUNCTION NXTMEM(MEMWDS)
C
C.. FUNCTION RETURNS THE IN NXTMEM THE NEXT AVAILABLE MEMORY SIZE
C.. (WHICH MUST BE EVENLY DIVISIBLE BY 'NWD4, NWD8, AND NWD16' AS
C.. DEFINED IN SETMEM
C
      NXTMEM=((MEMWDS+1999)/2000)*2000
      RETURN
      END
      SUBROUTINE COMPRS(ICODE,LIMIT)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C      THIS ROUTINE COMPRESSES ALL AVAILABLE MEMORY INTO A SINGLE BLOCK.
C IF *ICODE* IS ZERO, COMPRESSION OF MEMORY FROM WORD 1 TO *LIMIT* IS
C DONE;  OTHERWISE, COMPRESSION FROM *LDVAL* DOWN TO *LIMIT* IS DONE.
C
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      IF (ICODE.NE.0) GO TO 100
      NBLK=NUMBLK
      LTAB2=LOCTAB
   10 LTAB1=LTAB2
      IF (LTAB1.GE.LIMIT) GO TO 200
      IF (NBLK.EQ.1) GO TO 200
      NBLK=NBLK-1
      LTAB2=LTAB1+NTAB
      MORG=ISTACK(LTAB1+1)
      MSIZ=ISTACK(LTAB1+2)
      MUSE=NXTEVN(ISTACK(LTAB1+3))
      MSLP=ISTACK(LTAB1+6)
      IF ((MSIZ-MUSE).LE.MSLP) GO TO 10
      MUSE=MUSE+MSLP
C...  MOVE SUCCEEDING BLOCK DOWN
      MORG2=ISTACK(LTAB2+1)
      MUSE2=ISTACK(LTAB2+3)
      MADR2=ISTACK(LTAB2+4)
      IWSIZE=ISTACK(LTAB2+5)
      IF (MADR2.NE.0) GO TO 15
      IF (MUSE2.EQ.0) GO TO 20
   15 CPYKNT=CPYKNT+DFLOAT(MUSE2)
      CALL COPY4(ISTACK(NWOFF+MORG2+1),ISTACK(NWOFF+MORG+MUSE+1),MUSE2)
      ISTACK(LORG+MADR2)=(MORG+MUSE)/IWSIZE
   20 ISTACK(LTAB1+2)=MUSE
      ISTACK(LTAB2+1)=MORG+MUSE
      ISTACK(LTAB2+2)=ISTACK(LTAB2+2)+(MSIZ-MUSE)
      GO TO 10
C
C
  100 NBLK=NUMBLK
      LTAB2=LDVAL-NTAB
  110 LTAB1=LTAB2
      IF (LTAB1.LE.LIMIT) GO TO 200
      IF (NBLK.EQ.1) GO TO 200
      NBLK=NBLK-1
      LTAB2=LTAB1-NTAB
      MORG=ISTACK(LTAB1+1)
      MSIZ=ISTACK(LTAB1+2)
      MUSER=ISTACK(LTAB1+3)
      MUSE=NXTEVN(MUSER)
      MADR=ISTACK(LTAB1+4)
      IWSIZE=ISTACK(LTAB1+5)
      MSLP=ISTACK(LTAB1+6)
      IF ((MSIZ-MUSE).LE.MSLP) GO TO 110
      MUSE=MUSE+MSLP
      MSPC=MSIZ-MUSE
      CPYKNT=CPYKNT+DFLOAT(MUSER)
      CALL COPY4(ISTACK(NWOFF+MORG+1),ISTACK(NWOFF+MORG+MSPC+1),MUSER)
      ISTACK(LTAB1+1)=MORG+MSPC
      ISTACK(LTAB1+2)=MUSE
      ISTACK(LTAB2+2)=ISTACK(LTAB2+2)+MSPC
      IF (MADR.EQ.0) GO TO 110
      ISTACK(LORG+MADR)=(MORG+MSPC)/IWSIZE
      GO TO 110
C...  ALL DONE
  200 RETURN
      END
      LOGICAL FUNCTION MEMPTR(IPNTR)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C      THIS ROUTINE CHECKS WHETHER *IPNTR* IS A VALID BLOCK POINTER.
C IF IT IS VALID, *LTAB* IS SET TO POINT TO THE CORRESPONDING ENTRY IN
C THE BLOCK TABLE.
C
C... IPNTR IS AN ARRAY TO AVOID 'CALL BY VALUE' PROBLEMS (SEE SETMEM)
      DIMENSION IPNTR(1)
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      MEMPTR=.FALSE.
      LTAB=LOCTAB
      LOCPNT=LOCF(IPNTR(1))
      DO 20 I=1,NUMBLK
      IF (LOCPNT.NE.ISTACK(LTAB+4)) GO TO 10
      IF (IPNTR(1)*ISTACK(LTAB+5).NE.ISTACK(LTAB+1)) GO TO 10
      MEMPTR=.TRUE.
      GO TO 30
   10 LTAB=LTAB+NTAB
   20 CONTINUE
   30 RETURN
      END
      SUBROUTINE DMPMEM(IPNTR)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C      THIS ROUTINE PRINTS OUT THE CURRENT MEMORY ALLOCATION MAP.
C *IPNTR* IS THE TABLE POINTER OF THE CURRENT MEMORY MANAGER CALL
C
C SPICE VERSION 2G.6  SCCSID=TABINF 3/15/83
      COMMON /TABINF/ IELMNT,ISBCKT,NSBCKT,IUNSAT,NUNSAT,ITEMPS,NUMTEM,
     1   ISENS,NSENS,IFOUR,NFOUR,IFIELD,ICODE,IDELIM,ICOLUM,INSIZE,
     2   JUNODE,LSBKPT,NUMBKP,IORDER,JMNODE,IUR,IUC,ILC,ILR,NUMOFF,ISR,
     3   NMOFFC,ISEQ,ISEQ1,NEQN,NODEVS,NDIAG,ISWAP,IEQUA,MACINS,LVNIM1,
     4   LX0,LVN,LYNL,LYU,LYL,LX1,LX2,LX3,LX4,LX5,LX6,LX7,LD0,LD1,LTD,
     5   IMYNL,IMVN,LCVN,NSNOD,NSMAT,NSVAL,ICNOD,ICMAT,ICVAL,
     6   LOUTPT,LPOL,LZER,IRSWPF,IRSWPR,ICSWPF,ICSWPR,IRPT,JCPT,
     7   IROWNO,JCOLNO,NTTBR,NTTAR,LVNTMP
C SPICE VERSION 2G.6  SCCSID=STATUS 3/15/83
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      DIMENSION IPNTR(1)
      DIMENSION APTR(75)
      DATA APTR /6HIELMNT,6HISBCKT,6HNSBCKT,6HIUNSAT,6HNUNSAT,6HITEMPS,
     1 6HNUMTEM,6HISENS ,6HNSENS ,6HIFOUR ,6HNFOUR ,6HIFIELD,
     2 6HICODE ,6HIDELIM,6HICOLUM,6HINSIZE,
     3 6HJUNODE,6HLSBKPT,6HNUMBKP,6HIORDER,6HJMNODE,
     4 6HIUR   ,6HIUC   ,6HILC   ,6HILR   ,6HNUMOFF,6HISR   ,
     5 6HNMOFFC,6HISEQ  ,6HISEQ1  ,6HNEQN  ,6HNODEVS,
     6 6HNDIAG ,6HISWAP ,6HIEQUA ,6HMACINS,6HLVNIM1,
     7 6HLX0   ,6HLVN   ,6HLYNL  ,6HLYU   ,6HLYL   ,
     8 6HLX1   ,6HLX2   ,6HLX3   ,6HLX4   ,6HLX5   ,6HLX6   ,
     9 6HLX7   ,6HLD0   ,6HLD1   ,6HLTD   ,6HIMYNL ,6HIMVN  ,6HLCVN  ,
     * 6HNSNOD ,6HNSMAT ,6HNSVAL ,6HICNOD ,6HICMAT ,6HICVAL ,6HLOUTPT,
     * 6HLPOL  ,6HLZER  ,6HIRSWPF,6HIRSWPR,6HICSWPF,6HICSWPR,6HIRPT  ,
     * 6HJCPT  ,6HIROWNO,6HJCOLNO,6HNTTBR ,6HNTTAR ,6HLVNTMP/
      DATA ABLNK /1H /
C
      IADDR=LOCF(IELMNT)-1
      ITEMP=LOCF(IPNTR(1))-IADDR
      ANAM=ABLNK
      IF(ITEMP.GT.0.AND.ITEMP.LE.75) ANAM=APTR(ITEMP)
      IADR=LOCF(IPNTR(1))
      WRITE (IOFILE,5) ANAM,IADR,ICORE,MAXMEM,MEMAVL,LDVAL
    5 FORMAT('0CURRENT POINTER ',A6,'@ = Z',I6,/' CORSIZ=',I7,
     1  /' MAXMEM=',I7,/' AVLSPC=',I7,/' LDVAL=',I7,
     2  /1H0,24X,'MEMORY ALLOCATION MAP'/14X,'BLKNUM MEMORG MEMSIZ',
     3  '  MEMUSE USRPTR  ADDR    NAME')
      LTAB1=LOCTAB
      DO 20 I=1,NUMBLK
      MORG=ISTACK(LTAB1+1)
      MSIZ=ISTACK(LTAB1+2)
      MUSE=ISTACK(LTAB1+3)
      MADR=ISTACK(LTAB1+4)
      ANAM=ABLNK
      NDEX=MADR-IADDR
      IF(NDEX.GT.0.AND.NDEX.LE.75) ANAM=APTR(NDEX)
      JPTR=0
      IF (MADR.GT.0) JPTR=ISTACK(LORG+MADR)
      WRITE (IOFILE,11) I,MORG,MSIZ,MUSE,JPTR,MADR,ANAM
   11 FORMAT(13X,5I7,3X,I7,'Z',1X,A6)
      LTAB1=LTAB1+NTAB
   20 CONTINUE
      WRITE (IOFILE,21)
   21 FORMAT(1H0,24X,'END OF ALLOCATION MAP'/)
      RETURN
      END
      SUBROUTINE MEMORY
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
C SPICE VERSION 2G.6  SCCSID=FLAGS 3/15/83
      COMMON /FLAGS/ IPRNTA,IPRNTL,IPRNTM,IPRNTN,IPRNTO,LIMTIM,LIMPTS,
     1   LVLCOD,LVLTIM,ITL1,ITL2,ITL3,ITL4,ITL5,ITL6,IGOOF,NOGO,KEOF
      IF(ICORE.LE.MAXMEM) GO TO 10
    5 MEMERR=4
      RETURN
   10 CONTINUE
C
C  SET JOB FIELD LENGTH TO 'ICORE+LOCF(ISTACK(IFWA))'
C
      RETURN
      END
      SUBROUTINE CPYTB4(ITABO,ITABN)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     THIS ROUTINE COPIES A TABLE.  ITS USE IS MADE NECESSARY BY THE
C FACT THAT ONLY ONE POINTER IS ALLOWED PER TABLE.
C
C SPICE VERSION 2G.6  SCCSID=BLANK 3/15/83
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(64)
      COMPLEX CVALUE(32)
      EQUIVALENCE (VALUE(1),NODPLC(1),CVALUE(1))
C
C
      CALL SIZMEM(NODPLC(ITABO),ISIZE)
      CALL GETM4(NODPLC(ITABN),ISIZE)
      LOCO=NODPLC(ITABO)
      LOCN=NODPLC(ITABN)
      CALL COPY4(NODPLC(LOCO+1),NODPLC(LOCN+1),ISIZE)
      RETURN
      END
      SUBROUTINE CPYTB8(ITABO,ITABN)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     THIS ROUTINE COPIES A TABLE.  ITS USE IS MADE NECESSARY BY THE
C FACT THAT ONLY ONE POINTER IS ALLOWED PER TABLE.
C
C SPICE VERSION 2G.6  SCCSID=BLANK 3/15/83
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(64)
      COMPLEX CVALUE(32)
      EQUIVALENCE (VALUE(1),NODPLC(1),CVALUE(1))
C
C
      CALL SIZMEM(NODPLC(ITABO),ISIZE)
      CALL GETM8(NODPLC(ITABN),ISIZE)
      LOCO=NODPLC(ITABO)
      LOCN=NODPLC(ITABN)
      CALL COPY8(VALUE(LOCO+1),VALUE(LOCN+1),ISIZE)
      RETURN
      END
