C SPICE2G.6 -- ENGINE LAYER: SPARSE MATRIX AND LINEAR SOLVE
C Builds the node-admittance matrix's sparse structure, performs
C LU decomposition/forward-backward solve for DC and AC analysis,
C and provides the small complex-arithmetic helpers used throughout
C the engine.
C
      SUBROUTINE DCDCMP
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      REAL T1,T2
C
C     THIS ROUTINE SWAPS ROWS AND COLUMNS IN THE COEFFICIENT MATRIX ACCOR-
C DING TO THE NUMERICAL PIVOTING AND MINIMUM FILLIN TERMS.IT THEN PERFORMS
C AN IN-PLACE LU FACTORIZATION OF THE COEFFICIENT MATRIX.
C
C SPICE VERSION 2G.6  SCCSID=TABINF 3/15/83
      COMMON /TABINF/ IELMNT,ISBCKT,NSBCKT,IUNSAT,NUNSAT,ITEMPS,NUMTEM,
     1   ISENS,NSENS,IFOUR,NFOUR,IFIELD,ICODE,IDELIM,ICOLUM,INSIZE,
     2   JUNODE,LSBKPT,NUMBKP,IORDER,JMNODE,IUR,IUC,ILC,ILR,NUMOFF,ISR,
     3   NMOFFC,ISEQ,ISEQ1,NEQN,NODEVS,NDIAG,ISWAP,IEQUA,MACINS,LVNIM1,
     4   LX0,LVN,LYNL,LYU,LYL,LX1,LX2,LX3,LX4,LX5,LX6,LX7,LD0,LD1,LTD,
     5   IMYNL,IMVN,LCVN,NSNOD,NSMAT,NSVAL,ICNOD,ICMAT,ICVAL,
     6   LOUTPT,LPOL,LZER,IRSWPF,IRSWPR,ICSWPF,ICSWPR,IRPT,JCPT,
     7   IROWNO,JCOLNO,NTTBR,NTTAR,LVNTMP
C SPICE VERSION 2G.6  SCCSID=MISCEL 3/15/83
      COMMON /MISCEL/ ATIME,APROG(3),ADATE,ATITLE(10),DEFL,DEFW,DEFAD,
     1  DEFAS,RSTATS(50),IWIDTH,LWIDTH,NOPAGE
C SPICE VERSION 2G.6  SCCSID=CIRDAT 3/15/83
      COMMON /CIRDAT/ LOCATE(50),JELCNT(50),NUNODS,NCNODS,NUMNOD,NSTOP,
     1   NUT,NLT,NXTRM,NDIST,NTLIN,IBR,NUMVS,NUMALT,NUMCYC
C SPICE VERSION 2G.6  SCCSID=STATUS 3/15/83
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
C SPICE VERSION 2G.6  SCCSID=FLAGS 3/15/83
      COMMON /FLAGS/ IPRNTA,IPRNTL,IPRNTM,IPRNTN,IPRNTO,LIMTIM,LIMPTS,
     1   LVLCOD,LVLTIM,ITL1,ITL2,ITL3,ITL4,ITL5,ITL6,IGOOF,NOGO,KEOF
C SPICE VERSION 2G.6  SCCSID=KNSTNT 3/15/83
      COMMON /KNSTNT/ TWOPI,XLOG2,XLOG10,ROOT2,RAD,BOLTZ,CHARGE,CTOK,
     1   GMIN,RELTOL,ABSTOL,VNTOL,TRTOL,CHGTOL,EPS0,EPSSIL,EPSOX,
     2   PIVTOL,PIVREL
C SPICE VERSION 2G.6  SCCSID=DEBUG 3/15/83
      COMMON/DEBUG/ IDEBUG(20)
C SPICE VERSION 2G.6  SCCSID=BLANK 3/15/83
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(64)
      COMPLEX CVALUE(32)
      EQUIVALENCE (VALUE(1),NODPLC(1),CVALUE(1))
C
      CALL SECOND(T1)
      IF (IPIV.LE.0) GO TO 12
      IF (IDEBUG(11).LE.0) GO TO  3
      CALL DMPMAT(6HDCDCMP)
      IDEBUG(11)=IDEBUG(11)-1
    3 DO 10 I=2,NSTOP
      NO=0
      LOC=NODPLC(JCPT+I)
    5 IF (LOC.EQ.0) GO TO 7
      NO=NO+1
      LOC=NODPLC(JCPT+LOC)
      GO TO 5
    7 NODPLC(NUMOFF+I)=NO
      NO=0
      LOC=NODPLC(IRPT+I)
    8 IF (LOC.EQ.0) GO TO 9
      NO=NO+1
      LOC=NODPLC(IRPT+LOC)
      GO TO 8
    9 NODPLC(NMOFFC+I)=NO
   10 CONTINUE
   12 N=1
C
C     FIND NEXT PIVOT
C
   15 N=N+1
      IF (IPIV.GT.0) GO TO 20
      IF (IDEBUG(13).LE.0) GO TO 17
      CALL DMPMAT(6HDCDCM2)
      IDEBUG(13)=IDEBUG(13)-1
   17 IF (IDEBUG(14).LE.0) GO TO 18
      IF (MODE.NE.2) GO TO 18
      CALL DMPMAT(6HDCDCM3)
      IDEBUG(14)=IDEBUG(14)-1
   18 IF (IDEBUG(15).LE.0.OR.ICALC.LE.10) GO TO 19
      CALL DMPMAT(6HDCDCM4)
      IDEBUG(15)=IDEBUG(15)-1
   19 NXTI=N
      NXTJ=N
      GO TO 120
C
C     SEARCH THE CORESPONDING COLUMN FOR MAX ENTRY
C
   20 VMAX=0.0D0
      LOCI=N
   25 LOCI=NODPLC(IRPT+LOCI)
      IF (LOCI.EQ.0) GO TO 50
      I=NODPLC(IROWNO+LOCI)
      IF (I.LT.N) GO TO 25
   30 IF (DABS(VALUE(LVN+LOCI)).LE.VMAX) GO TO 25
      VMAX=DABS(VALUE(LVN+LOCI))
      GO TO 25
   50 IF (VMAX.GT.PIVTOL) GO TO 60
      WRITE(IOFILE,51) N,VMAX
   51 FORMAT('0*ERROR*:  MAXIMUM ENTRY IN THIS COLUMN AT STEP ',I4,' (',
     1   1PD12.6,') IS LESS THAN PIVTOL')
      IGOOF=1
      RETURN
   60 EPSREL=DMAX1(PIVREL*VMAX,PIVTOL)
      IF (N.GE.NSTOP) GO TO 200
      IF (IPIV.LE.0) GO TO 120
C
C     PIVOTING ON THE DIAGONAL
C
      MINOP=100000
      NXTI=0
      DO 70 I=N,NSTOP
      I1=NODPLC(IRSWPF+I)
      J1=NODPLC(ICSWPF+I)
      ISPOT=INDXX(I1,J1)
      IF (ISPOT.EQ.1) GO TO 70
      IF (DABS(VALUE(LVN+ISPOT)).LT.EPSREL) GO TO 70
      NOP=(NODPLC(NUMOFF+I)-1)*(NODPLC(NMOFFC+I)-1)
      IF (NOP.GE.MINOP) GO TO 70
      MINOP=NOP
      NXTI=I
      NXTJ=I
      IF (MINOP.LE.0) GO TO 95
   70 CONTINUE
      IF (NXTI.LE.0) GO TO 75
      IF (NXTI-N) 120,120,100
C
C     PIVOTING ON THE ENTIRE MATRIX
C
   75 DO 90 I=N,NSTOP
      LOC=I
   80 LOC=NODPLC(JCPT+LOC)
      IF (LOC.EQ.0) GO TO 90
      J=NODPLC(JCOLNO+LOC)
      IF (J.LT.N) GO TO 80
      IF (DABS(VALUE(LVN+LOC)).LT.EPSREL) GO TO 80
      NOP=(NODPLC(NUMOFF+I)-1)*(NODPLC(NMOFFC+J)-1)
      IF (NOP.GE.MINOP) GO TO 80
      MINOP=NOP
      NXTI=I
      NXTJ=J
      IF (MINOP.LE.0) GO TO 95
   90 CONTINUE
      IF (NXTI.GT.0) GO TO 95
      WRITE (IOFILE,92)
   92 FORMAT('0*ABORT*:  PIVOT NOT IN DCDCMP')
      IGOOF=1
      GO TO 200
   95 IF (NXTI.EQ.N.AND.NXTJ.EQ.N) GO TO 120
      IF (NXTI.EQ.N) GO TO 105
C
C     A PIVOT HAS BEEN FOUND
C
  100 LOAD=NODPLC(IRSWPF+NXTI)
      LR=NODPLC(IRSWPF+N)
      NODPLC(IRSWPF+NXTI)=LR
      NODPLC(IRSWPR+LR)=NXTI
      NODPLC(IRSWPF+N)=LOAD
      NODPLC(IRSWPR+LOAD)=N
      NOFF=NODPLC(NUMOFF+NXTI)
      NODPLC(NUMOFF+NXTI)=NODPLC(NUMOFF+N)
      NODPLC(NUMOFF+N)=NOFF
      IF (NXTJ.EQ.N) GO TO 110
  105 LOAD=NODPLC(ICSWPF+NXTJ)
      LC=NODPLC(ICSWPF+N)
      NODPLC(ICSWPF+NXTJ)=LC
      NODPLC(ICSWPR+LC)=NXTJ
      NODPLC(ICSWPF+N)=LOAD
      NODPLC(ICSWPR+LOAD)=N
      NOFF=NODPLC(NMOFFC+NXTJ)
      NODPLC(NMOFFC+NXTJ)=NODPLC(NMOFFC+N)
      NODPLC(NMOFFC+N)=NOFF
  110 CALL SWAPIJ(NXTI,N,NXTJ,N)
      NXTI=N
      NXTJ=N
C
C     CALCULATE CONTRIBUTION FROM NXTI, NXTJ AND FIND FILL-INS
C
  120 IF (N.GE.NSTOP) GO TO 200
      N1=NODPLC(IRSWPF+NXTI)
      N2=NODPLC(ICSWPF+NXTJ)
      LOCNN=INDXX(N1,N2)
      IF (IPIV.LE.0 .AND. DABS(VALUE(LVN+LOCNN)).LT.PIVTOL) GO TO 220
C
C     DOWN COL J
C
      LOCR=NODPLC(IRPT+LOCNN)
  125 IF (LOCR.EQ.0) GO TO 180
      I=NODPLC(IROWNO+LOCR)
      VALUE(LVN+LOCR)=VALUE(LVN+LOCR)/VALUE(LVN+LOCNN)
      LOCC=NODPLC(JCPT+LOCNN)
C
C     FOR EACH COLUMN ELEMENT LOOK UP ROW NXTI
C
  130 IF (LOCC.EQ.0) GO TO 170
      J=NODPLC(JCOLNO+LOCC)
C
C     CHECK FOR FILL-IN (I,J)
C
      IF (IPIV.LE.0) GO TO 135
      CALL SIZMEM(JCPT,ISIZE1)
      CALL RESERV(I,J)
      CALL SIZMEM(JCPT,ISIZE2)
      IF (ISIZE1.EQ.ISIZE2) GO TO 135
      CALL EXTMEM(LVN,1)
      NTTBR=NTTBR+1
      VALUE(LVN+NSTOP+NTTBR)=0.0D0
C
C     LOCATE ELEMENT (I,J)
C
  135 IF (J.LT.I) GO TO 145
      LOCIJ=LOCC
  140 LOCIJ=NODPLC(IRPT+LOCIJ)
      IF (NODPLC(IROWNO+LOCIJ).EQ.I) GO TO 155
      GO TO 140
  145 LOCIJ=LOCR
  150 LOCIJ=NODPLC(JCPT+LOCIJ)
      IF (NODPLC(JCOLNO+LOCIJ).EQ.J) GO TO 155
      GO TO 150
  155 VALUE(LVN+LOCIJ)=VALUE(LVN+LOCIJ)-
     1                  VALUE(LVN+LOCC)*VALUE(LVN+LOCR)
  160 LOCC=NODPLC(JCPT+LOCC)
      GO TO 130
  170 LOCR=NODPLC(IRPT+LOCR)
      IF (IPIV.LE.0) GO TO 125
      NODPLC(NUMOFF+I)=NODPLC(NUMOFF+I)-1
      GO TO 125
C
C     REDUCE NMOFFC FOR EACH ELEMENT IN COL NXTI
C
  180 IF (IPIV.LE.0) GO TO 15
      LOCC=NODPLC(JCPT+LOCNN)
  185 IF (LOCC.EQ.0) GO TO 15
      J=NODPLC(JCOLNO+LOCC)
      NODPLC(NMOFFC+J)=NODPLC(NMOFFC+J)-1
      LOCC=NODPLC(JCPT+LOCC)
      GO TO 185
C
C     DONE
C
  200 IF (IPIV.EQ.0) GO TO 210
      IF (IDEBUG(17).LE.0) GO TO 202
      CALL DMPMAT(6HDCDCM5)
      IDEBUG(17)=IDEBUG(17)-1
  202 CALL MATLOC
      RSTATS(49)=RSTATS(49)+1.0D0
      IPIV=0
      IF (LVLCOD.EQ.2) LVLCOD=3
      IFILL=NTTBR-NTTAR
      PERSPA=100.0D0*(1.0D0-DFLOAT(NTTBR)/DFLOAT(NSTOP*NSTOP))
C
C  CALCULATION OF OPERATION COUNT (OPERATION := `*' or `/'):
C
C     NOFFR := OFF-DIAGONAL ELEMENTS IN ROW, NOT INCLUDING DIAGONAL,
C                COUNTING ONLY THOSE ELEMENTS IN THE REMAINDER MATRIX
C     NOFFC := OFF-DIAGONAL ELEMENTS IN COLUMN, NOT INCLUDING DIAGONAL,
C                COUNTING ONLY THOSE ELEMENTS IN THE REMAINDER MATRIX
C
C     THEN WE HAVE
C
C        LU DECOMPOSITION     REQUIRES SIGMA(2,NSTOP-1) {NOFFC + NOFFC*NOFFR}
C        FORWARD SUBSTITUTION          SIGMA(2,NSTOP-1) {NOFFC + 1}   +   1
C        BACKWARD SUBSTITUTION         SIGMA(2,NSTOP-1) {NOFFR}
C
C     WHICH SUMS TO
C
C               SIGMA(2,NSTOP-1) {NOFFC + NOFFC*NOFFR + (NOFFC+1) + NOFFR} + 1
C         OR
C               SIGMA(2,NSTOP-1) {NOFFC*(NOFFR+2) + NOFFR + 1}   +   1
C
      IOPS=1
      NSTOP1=NSTOP-1
      DO 205 I=2,NSTOP1
      NOFFR=NODPLC(NUMOFF+I)-1
      NOFFC=NODPLC(NMOFFC+I)-1
      IOPS=IOPS+NOFFR+NOFFC*(NOFFR+2)+1
  205 CONTINUE
      RSTATS(20)=NSTOP
      RSTATS(21)=NTTAR
      RSTATS(22)=NTTBR
      RSTATS(23)=IFILL
      RSTATS(24)=0.0D0
      RSTATS(25)=NTTBR
      RSTATS(26)=IOPS
      RSTATS(27)=PERSPA
      GO TO 215
  210 IF (IDEBUG(18).LE.0) GO TO 212
      CALL DMPMAT(6HDCDCM6)
      IDEBUG(18)=IDEBUG(18)-1
  212 IF (IDEBUG(19).LE.0.OR.ICALC.LE.10) GO TO 215
      CALL DMPMAT(6HDCDCM7)
      IDEBUG(19)=IDEBUG(19)-1
  215 CALL SECOND(T2)
      RSTATS(50)=RSTATS(50)+T2-T1
       RETURN
  220 IPIV=1
      WRITE(IOFILE,221) N,NXTI,NXTJ,ITERNO,TIME
  221 FORMAT(' PIVOT CHANGE ON FLY: N= ',I5,' NXTI= ',I5,' NXTJ= ',
     1       I5,' ITERNO= ',I5,' TIME= ',1PD12.5)
      RSTATS(49)=RSTATS(49)+1.0D0
      GO TO 20
      END
      SUBROUTINE DCSOL
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      REAL T1,T2
C
C     THIS ROUTINE SOLVES THE SYSTEM OF CIRCUIT EQUATIONS BY PERFORMING
C A FORWARD AND BACKWARD SUBSTITUTION STEP USING THE PREVIOUSLY-COMPUTED
C LU FACTORS.
C
C SPICE VERSION 2G.6  SCCSID=TABINF 3/15/83
      COMMON /TABINF/ IELMNT,ISBCKT,NSBCKT,IUNSAT,NUNSAT,ITEMPS,NUMTEM,
     1   ISENS,NSENS,IFOUR,NFOUR,IFIELD,ICODE,IDELIM,ICOLUM,INSIZE,
     2   JUNODE,LSBKPT,NUMBKP,IORDER,JMNODE,IUR,IUC,ILC,ILR,NUMOFF,ISR,
     3   NMOFFC,ISEQ,ISEQ1,NEQN,NODEVS,NDIAG,ISWAP,IEQUA,MACINS,LVNIM1,
     4   LX0,LVN,LYNL,LYU,LYL,LX1,LX2,LX3,LX4,LX5,LX6,LX7,LD0,LD1,LTD,
     5   IMYNL,IMVN,LCVN,NSNOD,NSMAT,NSVAL,ICNOD,ICMAT,ICVAL,
     6   LOUTPT,LPOL,LZER,IRSWPF,IRSWPR,ICSWPF,ICSWPR,IRPT,JCPT,
     7   IROWNO,JCOLNO,NTTBR,NTTAR,LVNTMP
C SPICE VERSION 2G.6  SCCSID=MISCEL 3/15/83
      COMMON /MISCEL/ ATIME,APROG(3),ADATE,ATITLE(10),DEFL,DEFW,DEFAD,
     1  DEFAS,RSTATS(50),IWIDTH,LWIDTH,NOPAGE
C SPICE VERSION 2G.6  SCCSID=CIRDAT 3/15/83
      COMMON /CIRDAT/ LOCATE(50),JELCNT(50),NUNODS,NCNODS,NUMNOD,NSTOP,
     1   NUT,NLT,NXTRM,NDIST,NTLIN,IBR,NUMVS,NUMALT,NUMCYC
C SPICE VERSION 2G.6  SCCSID=BLANK 3/15/83
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(64)
      COMPLEX CVALUE(32)
      EQUIVALENCE (VALUE(1),NODPLC(1),CVALUE(1))
C
C  FORWARD SUBSTITUTION
C
      CALL SECOND(T1)
      DO 20 I=2,NSTOP
      LOC=I
      IORD=NODPLC(IRSWPF+I)
   10 LOC=NODPLC(JCPT+LOC)
      IF (NODPLC(JCOLNO+LOC).GE.I) GO TO 20
      J=NODPLC(JCOLNO+LOC)
      JORD=NODPLC(IRSWPF+J)
      VALUE(LVN+IORD)=VALUE(LVN+IORD)-
     1           VALUE(LVN+LOC)*VALUE(LVN+JORD)
      GO TO 10
   20 CONTINUE
C
C     BACK SUBSTITUTION
C
      I=NSTOP
      IORD=NODPLC(IRSWPF+I)
      JORD=NODPLC(ICSWPF+I)
      LOCNN=INDXX(IORD,JORD)
   30 VALUE(LVN+IORD)=VALUE(LVN+IORD)/VALUE(LVN+LOCNN)
      I=I-1
      IF (I.LE.1) GO TO 100
      IORD=NODPLC(IRSWPF+I)
      LOC=I
   35 LOC=NODPLC(JCPT+LOC)
   40 IF (NODPLC(JCOLNO+LOC).NE.I) GO TO 35
      LOCNN=LOC
   50 LOC=NODPLC(JCPT+LOC)
      IF (LOC.EQ.0) GO TO 30
      J=NODPLC(JCOLNO+LOC)
      JORD=NODPLC(IRSWPF+J)
      VALUE(LVN+IORD)=VALUE(LVN+IORD)-
     1           VALUE(LVN+LOC)*VALUE(LVN+JORD)
      GO TO 50
  100 CALL SECOND(T2)
      RSTATS(46)=RSTATS(46)+T2-T1
      RETURN
      END
      SUBROUTINE DMPMAT(ANAM)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C      THIS ROUTINE DUMPS OUT THE MATRIX AND ASSOCIATED POINTERS.
C
C SPICE VERSION 2G.6  SCCSID=TABINF 3/15/83
      COMMON /TABINF/ IELMNT,ISBCKT,NSBCKT,IUNSAT,NUNSAT,ITEMPS,NUMTEM,
     1   ISENS,NSENS,IFOUR,NFOUR,IFIELD,ICODE,IDELIM,ICOLUM,INSIZE,
     2   JUNODE,LSBKPT,NUMBKP,IORDER,JMNODE,IUR,IUC,ILC,ILR,NUMOFF,ISR,
     3   NMOFFC,ISEQ,ISEQ1,NEQN,NODEVS,NDIAG,ISWAP,IEQUA,MACINS,LVNIM1,
     4   LX0,LVN,LYNL,LYU,LYL,LX1,LX2,LX3,LX4,LX5,LX6,LX7,LD0,LD1,LTD,
     5   IMYNL,IMVN,LCVN,NSNOD,NSMAT,NSVAL,ICNOD,ICMAT,ICVAL,
     6   LOUTPT,LPOL,LZER,IRSWPF,IRSWPR,ICSWPF,ICSWPR,IRPT,JCPT,
     7   IROWNO,JCOLNO,NTTBR,NTTAR,LVNTMP
C SPICE VERSION 2G.6  SCCSID=MISCEL 3/15/83
      COMMON /MISCEL/ ATIME,APROG(3),ADATE,ATITLE(10),DEFL,DEFW,DEFAD,
     1  DEFAS,RSTATS(50),IWIDTH,LWIDTH,NOPAGE
C SPICE VERSION 2G.6  SCCSID=LINE 3/15/83
      COMMON /LINE/ ACHAR,AFIELD(15),OLDLIN(15),KNTRC,KNTLIM
C SPICE VERSION 2G.6  SCCSID=CIRDAT 3/15/83
      COMMON /CIRDAT/ LOCATE(50),JELCNT(50),NUNODS,NCNODS,NUMNOD,NSTOP,
     1   NUT,NLT,NXTRM,NDIST,NTLIN,IBR,NUMVS,NUMALT,NUMCYC
C SPICE VERSION 2G.6  SCCSID=MOSARG 3/15/83
      COMMON /MOSARG/ VTO,BETA,GAMMA,PHI,PHIB,COX,XNSUB,XNFS,XD,XJ,XLD,
     1   XLAMDA,UO,UEXP,VBP,UTRA,VMAX,XNEFF,XL,XW,VBI,VON,VDSAT,QSPOF,
     2   BETA0,BETA1,CDRAIN,XQCO,XQC,FNARRW,FSHORT,LEV
C SPICE VERSION 2G.6  SCCSID=STATUS 3/15/83
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
C SPICE VERSION 2G.6  SCCSID=FLAGS 3/15/83
      COMMON /FLAGS/ IPRNTA,IPRNTL,IPRNTM,IPRNTN,IPRNTO,LIMTIM,LIMPTS,
     1   LVLCOD,LVLTIM,ITL1,ITL2,ITL3,ITL4,ITL5,ITL6,IGOOF,NOGO,KEOF
C SPICE VERSION 2G.6  SCCSID=KNSTNT 3/15/83
      COMMON /KNSTNT/ TWOPI,XLOG2,XLOG10,ROOT2,RAD,BOLTZ,CHARGE,CTOK,
     1   GMIN,RELTOL,ABSTOL,VNTOL,TRTOL,CHGTOL,EPS0,EPSSIL,EPSOX,
     2   PIVTOL,PIVREL
C SPICE VERSION 2G.6  SCCSID=MEMMGR 3/15/83
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
C SPICE VERSION 2G.6  SCCSID=DC 3/15/83
      COMMON /DC/ TCSTAR(2),TCSTOP(2),TCINCR(2),ICVFLG,ITCELM(2),KSSOP,
     1   KINEL,KIDIN,KOVAR,KIDOUT
C SPICE VERSION 2G.6  SCCSID=AC 3/15/83
      COMMON /AC/ FSTART,FSTOP,FINCR,SKW2,REFPRL,SPW2,JACFLG,IDFREQ,
     1   INOISE,NOSPRT,NOSOUT,NOSIN,IDIST,IDPRT
C SPICE VERSION 2G.6  SCCSID=TRAN 3/15/83
      COMMON /TRAN/ TSTEP,TSTOP,TSTART,DELMAX,TDMAX,FORFRE,JTRFLG
C SPICE VERSION 2G.6  SCCSID=OUTINF 3/15/83
      COMMON /OUTINF/ XINCR,STRING(15),XSTART,YVAR(8),ITAB(8),ITYPE(8),
     1   ILOGY(8),NPOINT,NUMOUT,KNTR,NUMDGT
C SPICE VERSION 2G.6  SCCSID=CJE 3/15/83
      COMMON /CJE/ MAXTIM,ITIME,ICOST
C SPICE VERSION 2G.6  SCCSID=DEBUG 3/15/83
      COMMON/DEBUG/ IDEBUG(20)
C SPICE VERSION 2G.6  SCCSID=BLANK 3/15/83
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(64)
      COMPLEX CVALUE(32)
      EQUIVALENCE (VALUE(1),NODPLC(1),CVALUE(1))
C
C
      WRITE (IOFILE,10) ANAM,MODE,MODEDC,
     1 TIME,DELTA,ICALC,ITERNO,INITF,IPIV,IORD,NONCON,IGOOF,NOGO
   10 FORMAT('0*DEBUG*:  DMPMT CALLED BY ',A8,/,
     1   ' *DEBUG*:  MODE, MDC, TIME, DELTA, ICALC, ITR#, INITF,',
     2             ' PIV, ORD, NCON, IGOOF, NOGO =',/,
     3   ' *DEBUG*:  ',2I5,1P2D10.2,8I5)
      CALL DMPMEM(5HDMPMT)
C
C  DUMP OUT THE *WHOLE* THING
C
      CALL SIZMEM(IRPT,IRPTS)
      WRITE (IOFILE,16) NSTOP,NTTBR,IRPTS
   16 FORMAT(' *DEBUG*:  NSTOP, NTTBR, SIZE(IRPT) = ',3I6,/,
     1   ' *DEBUG*:   INDEX  IRPT  IROW  JCOL  JCPT       VALUE',
     2          10X,' INDEX  IRPT  IROW  JCOL  JCPT       VALUE')
      J=(IRPTS+1)/2
      ISTOP=J
      DO 30 I=1,ISTOP
      J=J+1
      WRITE (IOFILE,26)
     1   I,NODPLC(IRPT+I),NODPLC(IROWNO+I),NODPLC(JCOLNO+I),
     2   NODPLC(JCPT+I),VALUE(LVN+I),
     3   J,NODPLC(IRPT+J),NODPLC(IROWNO+J),NODPLC(JCOLNO+J),
     4   NODPLC(JCPT+J),VALUE(LVN+J)
   26 FORMAT(' *DEBUG*:  ',5I6,1PD12.4,10X,5I6,1PD12.4)
   30 CONTINUE
CC 51 FORMAT(" *DEBUG*:  IRPT   = ",18I6)
CC    WRITE (IOFILE,56) (NODPLC(IROWNO+I),I=1,IRPTS)
CC 56 FORMAT(" *DEBUG*:  IROWNO = ",18I6)
CC    WRITE (IOFILE,61) (NODPLC(JCOLNO+I),I=1,IRPTS)
CC 61 FORMAT(" *DEBUG*:  JCOLNO = ",18I6)
CC    WRITE (IOFILE,66) (NODPLC(JCPT  +I),I=1,IRPTS)
CC 66 FORMAT(" *DEBUG*:  JCPT   = ",18I6)
      WRITE (IOFILE,71) (NODPLC(IRSWPF+I),I=1,NSTOP)
   71 FORMAT(' *DEBUG*:  IRSWPF = ',18I6)
      WRITE (IOFILE,76) (NODPLC(IRSWPR+I),I=1,NSTOP)
   76 FORMAT(' *DEBUG*:  IRSWPR = ',18I6)
      WRITE (IOFILE,81) (NODPLC(ICSWPF+I),I=1,NSTOP)
   81 FORMAT(' *DEBUG*:  ICSWPF = ',18I6)
      WRITE (IOFILE,86) (NODPLC(ICSWPR+I),I=1,NSTOP)
   86 FORMAT(' *DEBUG*:  ICSWPR = ',18I6)
C
C
  500 RETURN
      END
      INTEGER FUNCTION INDXX(NODE1,NODE2)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     THIS ROUTINE MAPS A (ROW, COLUMN) MATRIX TERM SPECIFICATION INTO
C THE OFFSET FROM THE ORIGIN OF THE MATRIX STORAGE AT WHICH THE TERM IS
C ACTUALLY LOCATED.
C
C SPICE VERSION 2G.6  SCCSID=TABINF 3/15/83
      COMMON /TABINF/ IELMNT,ISBCKT,NSBCKT,IUNSAT,NUNSAT,ITEMPS,NUMTEM,
     1   ISENS,NSENS,IFOUR,NFOUR,IFIELD,ICODE,IDELIM,ICOLUM,INSIZE,
     2   JUNODE,LSBKPT,NUMBKP,IORDER,JMNODE,IUR,IUC,ILC,ILR,NUMOFF,ISR,
     3   NMOFFC,ISEQ,ISEQ1,NEQN,NODEVS,NDIAG,ISWAP,IEQUA,MACINS,LVNIM1,
     4   LX0,LVN,LYNL,LYU,LYL,LX1,LX2,LX3,LX4,LX5,LX6,LX7,LD0,LD1,LTD,
     5   IMYNL,IMVN,LCVN,NSNOD,NSMAT,NSVAL,ICNOD,ICMAT,ICVAL,
     6   LOUTPT,LPOL,LZER,IRSWPF,IRSWPR,ICSWPF,ICSWPR,IRPT,JCPT,
     7   IROWNO,JCOLNO,NTTBR,NTTAR,LVNTMP
C SPICE VERSION 2G.6  SCCSID=CIRDAT 3/15/83
      COMMON /CIRDAT/ LOCATE(50),JELCNT(50),NUNODS,NCNODS,NUMNOD,NSTOP,
     1   NUT,NLT,NXTRM,NDIST,NTLIN,IBR,NUMVS,NUMALT,NUMCYC
C SPICE VERSION 2G.6  SCCSID=BLANK 3/15/83
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(64)
      COMPLEX CVALUE(32)
      EQUIVALENCE (VALUE(1),NODPLC(1),CVALUE(1))
C
      IF (NODE1.EQ.1) GO TO 100
      IF (NODE2.EQ.1) GO TO 100
C
      N1=NODPLC(IRSWPR+NODE1)
      N2=NODPLC(ICSWPR+NODE2)
      IF (N1-N2) 10,10,30
C
C     SEARCH COL N2
C
   10 LOC=N2
   15 LOC=NODPLC(IRPT+LOC)
      IF (LOC.EQ.0) GO TO 100
      IF (NODPLC(IROWNO+LOC)-N1) 15,20,15
   20 INDXX=LOC
      RETURN
C
C     SEARCH ROW N1
C
   30 LOC=N1
   35 LOC=NODPLC(JCPT+LOC)
      IF (LOC.EQ.0) GO TO 100
      IF (NODPLC(JCOLNO+LOC)-N2) 35,40,35
   40 INDXX=LOC
      RETURN
C
C     UNUSED LOCATION
C
  100 INDXX=1
      RETURN
      END
      SUBROUTINE SWAPIJ(I1,I2,J1,J2)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C SPICE VERSION 2G.6  SCCSID=TABINF 3/15/83
      COMMON /TABINF/ IELMNT,ISBCKT,NSBCKT,IUNSAT,NUNSAT,ITEMPS,NUMTEM,
     1   ISENS,NSENS,IFOUR,NFOUR,IFIELD,ICODE,IDELIM,ICOLUM,INSIZE,
     2   JUNODE,LSBKPT,NUMBKP,IORDER,JMNODE,IUR,IUC,ILC,ILR,NUMOFF,ISR,
     3   NMOFFC,ISEQ,ISEQ1,NEQN,NODEVS,NDIAG,ISWAP,IEQUA,MACINS,LVNIM1,
     4   LX0,LVN,LYNL,LYU,LYL,LX1,LX2,LX3,LX4,LX5,LX6,LX7,LD0,LD1,LTD,
     5   IMYNL,IMVN,LCVN,NSNOD,NSMAT,NSVAL,ICNOD,ICMAT,ICVAL,
     6   LOUTPT,LPOL,LZER,IRSWPF,IRSWPR,ICSWPF,ICSWPR,IRPT,JCPT,
     7   IROWNO,JCOLNO,NTTBR,NTTAR,LVNTMP
C SPICE VERSION 2G.6  SCCSID=BLANK 3/15/83
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(64)
      COMPLEX CVALUE(32)
      EQUIVALENCE (VALUE(1),NODPLC(1),CVALUE(1))
C
C     SWAP ROWS I1 AND I2
C
      LOC1=NODPLC(JCPT+I1)
      LOC2=NODPLC(JCPT+I2)
      NODPLC(JCPT+I1)=LOC2
      NODPLC(JCPT+I2)=LOC1
C
C     CHECK IF END OF ROW
C
    5 IF (LOC1.LE.0.AND.LOC2.LE.0) GO TO 80
C
C     CHECK SWAP TYPE
C
      IF (LOC1.EQ.0) GO TO 20
      IF (LOC2.EQ.0) GO TO 10
      IF (NODPLC(JCOLNO+LOC1)-NODPLC(JCOLNO+LOC2)) 10,15,20
   10 KTYPE=-1
      J=NODPLC(JCOLNO+LOC1)
      GO TO 25
   15 KTYPE=0
      J=NODPLC(JCOLNO+LOC1)
      GO TO 25
   20 KTYPE=1
      J=NODPLC(JCOLNO+LOC2)
C
C     FIND POINTER TO ENTRY (I1,J)
C
   25 LOC=J
   30 LSAV1=LOC
      LOC=NODPLC(IRPT+LOC)
      IF (LOC.EQ.0) GO TO 40
      IF ((NODPLC(IROWNO+LOC)-I1).LT.0) GO TO 30
C
C     FIND POINTER TO ENTRY (I2,J)
C
   40 LOC=J
   45 LSAV2=LOC
      LOC=NODPLC(IRPT+LOC)
      IF (LOC.EQ.0) GO TO 55
      IF ((NODPLC(IROWNO+LOC)-I2).LT.0) GO TO 45
C
C     BRANCH FOR COL J IN ROW I1, IN BOTH ROW I1 AND I2, OR IN ROW I2
C
   55 IF (KTYPE) 60,70,75
C
C     ENTRY (I1,J)
C
   60 IF (LSAV1.EQ.LSAV2) GO TO 65
      LOC=NODPLC(IRPT+LSAV2)
      NODPLC(IRPT+LSAV2)=LOC1
      NODPLC(IRPT+LSAV1)=NODPLC(IRPT+LOC1)
      NODPLC(IRPT+LOC1)=LOC
   65 NODPLC(IROWNO+LOC1)=I2
      LOC1=NODPLC(JCPT+LOC1)
      GO TO 5
C
C     ENTRIES (I1,J) AND (I2,J)
C
   70 NODPLC(IRPT+LSAV1)=LOC2
      NODPLC(IRPT+LSAV2)=LOC1
      LOC=NODPLC(IRPT+LOC1)
      NODPLC(IRPT+LOC1)=NODPLC(IRPT+LOC2)
      NODPLC(IRPT+LOC2)=LOC
      NODPLC(IROWNO+LOC1)=I2
      NODPLC(IROWNO+LOC2)=I1
      LOC1=NODPLC(JCPT+LOC1)
      LOC2=NODPLC(JCPT+LOC2)
      GO TO 5
C
C     ENTRY (I2,J)
C
   75 IF (LSAV1.EQ.LSAV2) GO TO 78
      LOC=NODPLC(IRPT+LSAV1)
      NODPLC(IRPT+LSAV1)=LOC2
      NODPLC(IRPT+LSAV2)=NODPLC(IRPT+LOC2)
      NODPLC(IRPT+LOC2)=LOC
   78 NODPLC(IROWNO+LOC2)=I1
      LOC2=NODPLC(JCPT+LOC2)
      GO TO 5
C
C     SWAP COLUMNS J1 AND J2
C
   80 LOC1=NODPLC(IRPT+J1)
      LOC2=NODPLC(IRPT+J2)
      NODPLC(IRPT+J1)=LOC2
      NODPLC(IRPT+J2)=LOC1
C
C     CHECK FOR END OF COLUMN
C
   85 IF (LOC1.LE.0.AND.LOC2.LE.0) GO TO 160
C
C     CHECK SWAP TYPE
C
      IF (LOC1.EQ.0) GO TO 100
      IF (LOC2.EQ.0) GO TO 90
      IF (NODPLC(IROWNO+LOC1)-NODPLC(IROWNO+LOC2)) 90,95,100
   90 KTYPE=-1
      I=NODPLC(IROWNO+LOC1)
      GO TO 105
   95 KTYPE=0
      I=NODPLC(IROWNO+LOC1)
      GO TO 105
  100 KTYPE=1
      I=NODPLC(IROWNO+LOC2)
C
C     FIND POINTER TO ENTRY (I,J1)
C
  105 LOC=I
  110 LSAV1=LOC
      LOC=NODPLC(JCPT+LOC)
      IF (LOC.EQ.0) GO TO 120
      IF ((NODPLC(JCOLNO+LOC)-J1).LT.0) GO TO 110
C
C     FIND POINTER TO ENTRY (I,J2)
C
  120 LOC=I
  125 LSAV2=LOC
      LOC=NODPLC(JCPT+LOC)
      IF(LOC.EQ.0) GO TO 135
      IF ((NODPLC(JCOLNO+LOC)-J2).LT.0) GO TO 125
C
C     BRANCH FOR ROW I IN COL J1, IN BOTH COL"S J1 AND J2, OR IN COL J2
C
  135 IF (KTYPE) 140,150,155
C
C     ENTRY (I,J1)
C
  140 IF (LSAV1.EQ.LSAV2) GO TO 145
      LOC=NODPLC(JCPT+LSAV2)
      NODPLC(JCPT+LSAV2)=LOC1
      NODPLC(JCPT+LSAV1)=NODPLC(JCPT+LOC1)
      NODPLC(JCPT+LOC1)=LOC
  145 NODPLC(JCOLNO+LOC1)=J2
      LOC1=NODPLC(IRPT+LOC1)
      GO TO 85
C
C     ENTRIES (I1,J) AND (I2,J)
C
  150 NODPLC(JCPT+LSAV1)=LOC2
      NODPLC(JCPT+LSAV2)=LOC1
      LOC=NODPLC(JCPT+LOC1)
      NODPLC(JCPT+LOC1)=NODPLC(JCPT+LOC2)
      NODPLC(JCPT+LOC2)=LOC
      NODPLC(JCOLNO+LOC1)=J2
      NODPLC(JCOLNO+LOC2)=J1
      LOC1=NODPLC(IRPT+LOC1)
      LOC2=NODPLC(IRPT+LOC2)
      GO TO 85
C
C     ENTRY (I,J2)
C
  155 IF (LSAV1.EQ.LSAV2) GO TO 158
      LOC=NODPLC(JCPT+LSAV1)
      NODPLC(JCPT+LSAV1)=LOC2
      NODPLC(JCPT+LSAV2)=NODPLC(JCPT+LOC2)
      NODPLC(JCPT+LOC2)=LOC
  158 NODPLC(JCOLNO+LOC2)=J1
      LOC2=NODPLC(IRPT+LOC2)
      GO TO 85
  160 RETURN
      END
      SUBROUTINE RESERV (NODE1,NODE2)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     THIS ROUTINE RECORDS THE FACT THAT THE (NODE1, NODE2) ELEMENT OF
C THE CIRCUIT EQUATION COEFFICIENT MATRIX IS NONZERO.
C
C SPICE VERSION 2G.6  SCCSID=TABINF 3/15/83
      COMMON /TABINF/ IELMNT,ISBCKT,NSBCKT,IUNSAT,NUNSAT,ITEMPS,NUMTEM,
     1   ISENS,NSENS,IFOUR,NFOUR,IFIELD,ICODE,IDELIM,ICOLUM,INSIZE,
     2   JUNODE,LSBKPT,NUMBKP,IORDER,JMNODE,IUR,IUC,ILC,ILR,NUMOFF,ISR,
     3   NMOFFC,ISEQ,ISEQ1,NEQN,NODEVS,NDIAG,ISWAP,IEQUA,MACINS,LVNIM1,
     4   LX0,LVN,LYNL,LYU,LYL,LX1,LX2,LX3,LX4,LX5,LX6,LX7,LD0,LD1,LTD,
     5   IMYNL,IMVN,LCVN,NSNOD,NSMAT,NSVAL,ICNOD,ICMAT,ICVAL,
     6   LOUTPT,LPOL,LZER,IRSWPF,IRSWPR,ICSWPF,ICSWPR,IRPT,JCPT,
     7   IROWNO,JCOLNO,NTTBR,NTTAR,LVNTMP
C SPICE VERSION 2G.6  SCCSID=FLAGS 3/15/83
      COMMON /FLAGS/ IPRNTA,IPRNTL,IPRNTM,IPRNTN,IPRNTO,LIMTIM,LIMPTS,
     1   LVLCOD,LVLTIM,ITL1,ITL2,ITL3,ITL4,ITL5,ITL6,IGOOF,NOGO,KEOF
C SPICE VERSION 2G.6  SCCSID=BLANK 3/15/83
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(64)
      COMPLEX CVALUE(32)
      EQUIVALENCE (VALUE(1),NODPLC(1),CVALUE(1))
C
      LOGICAL MEMPTR
C
      IF (NOGO.NE.0) GO TO 300
C...  TEST FOR GROUND
      IF (NODE1.EQ.1) GO TO 300
      IF (NODE2.EQ.1) GO TO 300
C
C     RESERVE (NODE1,NODE2) IN ROW NODE1 AT COL POSN NODE2
C
      LOC=NODE1
   10 LOCJ=LOC
      LOC=NODPLC(JCPT+LOC)
      IF (LOC.EQ.0) GO TO 20
      IF (NODPLC(JCOLNO+LOC)-NODE2) 10,300,20
   20 CALL SIZMEM(JCPT,ISIZE)
      NEWLOC=ISIZE+1
      NODPLC(NUMOFF+NODE1)=NODPLC(NUMOFF+NODE1)+1
      NODPLC(NMOFFC+NODE2)=NODPLC(NMOFFC+NODE2)+1
      CALL EXTMEM(JCPT,1)
      CALL EXTMEM(JCOLNO,1)
      NODPLC(JCPT+LOCJ)=NEWLOC
      NODPLC(JCPT+NEWLOC)=LOC
      NODPLC(JCOLNO+NEWLOC)=NODE2
C
C     RESERVE (NODE1,NODE2) IN COL NODE2 AT ROW POSN NODE1
C
      LOC=NODE2
   30 LOCI=LOC
      LOC=NODPLC(IRPT+LOC)
      IF (LOC.EQ.0) GO TO 40
      IF (NODPLC(IROWNO+LOC)-NODE1) 30,300,40
   40 CALL EXTMEM(IRPT,1)
      CALL EXTMEM(IROWNO,1)
      NODPLC(IRPT+LOCI)=NEWLOC
      NODPLC(IRPT+NEWLOC)=LOC
      NODPLC(IROWNO+NEWLOC)=NODE1
C
C     MARK DIAGONAL
C
      IF (NODE1.NE.NODE2) GO TO 300
      IF (MEMPTR(NDIAG)) NODPLC(NDIAG+NODE1)=1
C
C     FINISHED
C
  300 RETURN
      END
      SUBROUTINE MATLOC
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     THIS ROUTINE STORES THE LOCATIONS OF THE VARIOUS MATRIX TERMS TO
C WHICH THE DIFFERENT CIRCUIT ELEMENTS CONTRIBUTE.
C
C SPICE VERSION 2G.6  SCCSID=TABINF 3/15/83
      COMMON /TABINF/ IELMNT,ISBCKT,NSBCKT,IUNSAT,NUNSAT,ITEMPS,NUMTEM,
     1   ISENS,NSENS,IFOUR,NFOUR,IFIELD,ICODE,IDELIM,ICOLUM,INSIZE,
     2   JUNODE,LSBKPT,NUMBKP,IORDER,JMNODE,IUR,IUC,ILC,ILR,NUMOFF,ISR,
     3   NMOFFC,ISEQ,ISEQ1,NEQN,NODEVS,NDIAG,ISWAP,IEQUA,MACINS,LVNIM1,
     4   LX0,LVN,LYNL,LYU,LYL,LX1,LX2,LX3,LX4,LX5,LX6,LX7,LD0,LD1,LTD,
     5   IMYNL,IMVN,LCVN,NSNOD,NSMAT,NSVAL,ICNOD,ICMAT,ICVAL,
     6   LOUTPT,LPOL,LZER,IRSWPF,IRSWPR,ICSWPF,ICSWPR,IRPT,JCPT,
     7   IROWNO,JCOLNO,NTTBR,NTTAR,LVNTMP
C SPICE VERSION 2G.6  SCCSID=CIRDAT 3/15/83
      COMMON /CIRDAT/ LOCATE(50),JELCNT(50),NUNODS,NCNODS,NUMNOD,NSTOP,
     1   NUT,NLT,NXTRM,NDIST,NTLIN,IBR,NUMVS,NUMALT,NUMCYC
C SPICE VERSION 2G.6  SCCSID=STATUS 3/15/83
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
C SPICE VERSION 2G.6  SCCSID=AC 3/15/83
      COMMON /AC/ FSTART,FSTOP,FINCR,SKW2,REFPRL,SPW2,JACFLG,IDFREQ,
     1   INOISE,NOSPRT,NOSOUT,NOSIN,IDIST,IDPRT
C SPICE VERSION 2G.6  SCCSID=BLANK 3/15/83
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(64)
      COMPLEX CVALUE(32)
      EQUIVALENCE (VALUE(1),NODPLC(1),CVALUE(1))
C
C  RESISTORS
C
      LOC=LOCATE(1)
  690 IF ((LOC.EQ.0).OR.(NODPLC(LOC+8).NE.0)) GO TO 700
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      NODPLC(LOC+4)=INDXX(NODE1,NODE2)
      NODPLC(LOC+5)=INDXX(NODE2,NODE1)
      NODPLC(LOC+6)=INDXX(NODE1,NODE1)
      NODPLC(LOC+7)=INDXX(NODE2,NODE2)
      LOC=NODPLC(LOC)
      GO TO 690
C
C  CAPACITORS
C
  700 LOC=LOCATE(2)
  710 IF ((LOC.EQ.0).OR.(NODPLC(LOC+12).NE.0)) GO TO 720
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      NODPLC(LOC+5)=INDXX(NODE1,NODE2)
      NODPLC(LOC+6)=INDXX(NODE2,NODE1)
      NODPLC(LOC+10)=INDXX(NODE1,NODE1)
      NODPLC(LOC+11)=INDXX(NODE2,NODE2)
      LOC=NODPLC(LOC)
      GO TO 710
C
C  INDUCTORS
C
  720 LOC=LOCATE(3)
  730 IF ((LOC.EQ.0).OR.(NODPLC(LOC+14).NE.0)) GO TO 740
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      IBR=NODPLC(LOC+5)
      NODPLC(LOC+6)=INDXX(NODE1,IBR)
      NODPLC(LOC+7)=INDXX(NODE2,IBR)
      NODPLC(LOC+8)=INDXX(IBR,NODE1)
      NODPLC(LOC+9)=INDXX(IBR,NODE2)
      NODPLC(LOC+13)=INDXX(IBR,IBR)
      LOC=NODPLC(LOC)
      GO TO 730
C
C  MUTUAL INDUCTANCES
C
  740 LOC=LOCATE(4)
  750 IF ((LOC.EQ.0).OR.(NODPLC(LOC+6).NE.0)) GO TO 760
      NL1=NODPLC(LOC+2)
      NL2=NODPLC(LOC+3)
      IBR1=NODPLC(NL1+5)
      IBR2=NODPLC(NL2+5)
      NODPLC(LOC+4)=INDXX(IBR1,IBR2)
      NODPLC(LOC+5)=INDXX(IBR2,IBR1)
      LOC=NODPLC(LOC)
      GO TO 750
C
C  NONLINEAR VOLTAGE CONTROLLED CURRENT SOURCES
C
  760 LOC=LOCATE(5)
  762 IF ((LOC.EQ.0).OR.(NODPLC(LOC+13).NE.0)) GO TO 764
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      NDIM=NODPLC(LOC+4)
      LNOD=NODPLC(LOC+6)
      LMAT=NODPLC(LOC+7)
      DO 763 I=1,NDIM
      NODE3=NODPLC(LNOD+1)
      NODE4=NODPLC(LNOD+2)
      LNOD=LNOD+2
      NODPLC(LMAT+1)=INDXX(NODE1,NODE3)
      NODPLC(LMAT+2)=INDXX(NODE1,NODE4)
      NODPLC(LMAT+3)=INDXX(NODE2,NODE3)
      NODPLC(LMAT+4)=INDXX(NODE2,NODE4)
      LMAT=LMAT+4
  763 CONTINUE
      LOC=NODPLC(LOC)
      GO TO 762
C
C  NONLINEAR VOLTAGE CONTROLLED VOLTAGE SOURCES
C
  764 LOC=LOCATE(6)
  766 IF ((LOC.EQ.0).OR.(NODPLC(LOC+14).NE.0)) GO TO 768
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      NDIM=NODPLC(LOC+4)
      IBR=NODPLC(LOC+6)
      LNOD=NODPLC(LOC+7)
      LMAT=NODPLC(LOC+8)
      NODPLC(LMAT+1)=INDXX(NODE1,IBR)
      NODPLC(LMAT+2)=INDXX(NODE2,IBR)
      NODPLC(LMAT+3)=INDXX(IBR,NODE1)
      NODPLC(LMAT+4)=INDXX(IBR,NODE2)
      LMAT=LMAT+4
      DO 767 I=1,NDIM
      NODE3=NODPLC(LNOD+1)
      NODE4=NODPLC(LNOD+2)
      LNOD=LNOD+2
      NODPLC(LMAT+1)=INDXX(IBR,NODE3)
      NODPLC(LMAT+2)=INDXX(IBR,NODE4)
      LMAT=LMAT+2
  767 CONTINUE
      LOC=NODPLC(LOC)
      GO TO 766
C
C  NONLINEAR CURRENT CONTROLLED CURRENT SOURCES
C
  768 LOC=LOCATE(7)
  770 IF ((LOC.EQ.0).OR.(NODPLC(LOC+13).NE.0)) GO TO 772
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      NDIM=NODPLC(LOC+4)
      LOCVS=NODPLC(LOC+6)
      LMAT=NODPLC(LOC+7)
      DO 771 I=1,NDIM
      LOCVST=NODPLC(LOCVS+I)
      IBR=NODPLC(LOCVST+6)
      NODPLC(LMAT+1)=INDXX(NODE1,IBR)
      NODPLC(LMAT+2)=INDXX(NODE2,IBR)
      LMAT=LMAT+2
  771 CONTINUE
      LOC=NODPLC(LOC)
      GO TO 770
C
C  NONLINEAR CURRENT CONTROLLED VOLTAGE SOURCES
C
  772 LOC=LOCATE(8)
  774 IF ((LOC.EQ.0).OR.(NODPLC(LOC+14).NE.0)) GO TO 780
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      NDIM=NODPLC(LOC+4)
      IBR=NODPLC(LOC+6)
      LOCVS=NODPLC(LOC+7)
      LMAT=NODPLC(LOC+8)
      NODPLC(LMAT+1)=INDXX(NODE1,IBR)
      NODPLC(LMAT+2)=INDXX(NODE2,IBR)
      NODPLC(LMAT+3)=INDXX(IBR,NODE1)
      NODPLC(LMAT+4)=INDXX(IBR,NODE2)
      LMAT=LMAT+4
      DO 775 I=1,NDIM
      LOCVST=NODPLC(LOCVS+I)
      KBR=NODPLC(LOCVST+6)
      NODPLC(LMAT+I)=INDXX(IBR,KBR)
  775 CONTINUE
      LOC=NODPLC(LOC)
      GO TO 774
C
C  VOLTAGE SOURCES
C
  780 LOC=LOCATE(9)
  790 IF ((LOC.EQ.0).OR.(NODPLC(LOC+11).NE.0)) GO TO 800
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      IPTR=NODPLC(LOC+6)
      NODPLC(LOC+7)=INDXX(NODE1,IPTR)
      NODPLC(LOC+8)=INDXX(NODE2,IPTR)
      NODPLC(LOC+9)=INDXX(IPTR,NODE1)
      NODPLC(LOC+10)=INDXX(IPTR,NODE2)
      LOC=NODPLC(LOC)
      GO TO 790
C
C  DIODES
C
  800 LOC=LOCATE(11)
  810 IF ((LOC.EQ.0).OR.(NODPLC(LOC+16).NE.0)) GO TO 820
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      NODE3=NODPLC(LOC+4)
      NODPLC(LOC+7)=INDXX(NODE1,NODE3)
      NODPLC(LOC+8)=INDXX(NODE2,NODE3)
      NODPLC(LOC+9)=INDXX(NODE3,NODE1)
      NODPLC(LOC+10)=INDXX(NODE3,NODE2)
      NODPLC(LOC+13)=INDXX(NODE1,NODE1)
      NODPLC(LOC+14)=INDXX(NODE2,NODE2)
      NODPLC(LOC+15)=INDXX(NODE3,NODE3)
      LOC=NODPLC(LOC)
      GO TO 810
C
C  TRANSISTORS
C
  820 LOC=LOCATE(12)
  830 IF ((LOC.EQ.0).OR.(NODPLC(LOC+36).NE.0)) GO TO 840
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      NODE3=NODPLC(LOC+4)
      NODE4=NODPLC(LOC+5)
      NODE5=NODPLC(LOC+6)
      NODE6=NODPLC(LOC+7)
      NODE7=NODPLC(LOC+30)
      NODPLC(LOC+10)=INDXX(NODE1,NODE4)
      NODPLC(LOC+11)=INDXX(NODE2,NODE5)
      NODPLC(LOC+12)=INDXX(NODE3,NODE6)
      NODPLC(LOC+13)=INDXX(NODE4,NODE1)
      NODPLC(LOC+14)=INDXX(NODE4,NODE5)
      NODPLC(LOC+15)=INDXX(NODE4,NODE6)
      NODPLC(LOC+16)=INDXX(NODE5,NODE2)
      NODPLC(LOC+17)=INDXX(NODE5,NODE4)
      NODPLC(LOC+18)=INDXX(NODE5,NODE6)
      NODPLC(LOC+19)=INDXX(NODE6,NODE3)
      NODPLC(LOC+20)=INDXX(NODE6,NODE4)
      NODPLC(LOC+21)=INDXX(NODE6,NODE5)
      NODPLC(LOC+24)=INDXX(NODE1,NODE1)
      NODPLC(LOC+25)=INDXX(NODE2,NODE2)
      NODPLC(LOC+26)=INDXX(NODE3,NODE3)
      NODPLC(LOC+27)=INDXX(NODE4,NODE4)
      NODPLC(LOC+28)=INDXX(NODE5,NODE5)
      NODPLC(LOC+29)=INDXX(NODE6,NODE6)
      NODPLC(LOC+31)=INDXX(NODE7,NODE7)
      NODPLC(LOC+32)=INDXX(NODE4,NODE7)
      NODPLC(LOC+33)=INDXX(NODE7,NODE4)
      NODPLC(LOC+34)=INDXX(NODE2,NODE4)
      NODPLC(LOC+35)=INDXX(NODE4,NODE2)
      LOC=NODPLC(LOC)
      GO TO 830
C
C  JFETS
C
  840 LOC=LOCATE(13)
  850 IF ((LOC.EQ.0).OR.(NODPLC(LOC+25).NE.0)) GO TO 860
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      NODE3=NODPLC(LOC+4)
      NODE4=NODPLC(LOC+5)
      NODE5=NODPLC(LOC+6)
      NODPLC(LOC+9)=INDXX(NODE1,NODE4)
      NODPLC(LOC+10)=INDXX(NODE2,NODE4)
      NODPLC(LOC+11)=INDXX(NODE2,NODE5)
      NODPLC(LOC+12)=INDXX(NODE3,NODE5)
      NODPLC(LOC+13)=INDXX(NODE4,NODE1)
      NODPLC(LOC+14)=INDXX(NODE4,NODE2)
      NODPLC(LOC+15)=INDXX(NODE4,NODE5)
      NODPLC(LOC+16)=INDXX(NODE5,NODE2)
      NODPLC(LOC+17)=INDXX(NODE5,NODE3)
      NODPLC(LOC+18)=INDXX(NODE5,NODE4)
      NODPLC(LOC+20)=INDXX(NODE1,NODE1)
      NODPLC(LOC+21)=INDXX(NODE2,NODE2)
      NODPLC(LOC+22)=INDXX(NODE3,NODE3)
      NODPLC(LOC+23)=INDXX(NODE4,NODE4)
      NODPLC(LOC+24)=INDXX(NODE5,NODE5)
      LOC=NODPLC(LOC)
      GO TO 850
C
C  MOSFETS
C
  860 LOC=LOCATE(14)
  870 IF ((LOC.EQ.0).OR.(NODPLC(LOC+33).NE.0)) GO TO 900
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      NODE3=NODPLC(LOC+4)
      NODE4=NODPLC(LOC+5)
      NODE5=NODPLC(LOC+6)
      NODE6=NODPLC(LOC+7)
      NODPLC(LOC+10)=INDXX(NODE1,NODE5)
      NODPLC(LOC+11)=INDXX(NODE2,NODE4)
      NODPLC(LOC+12)=INDXX(NODE2,NODE5)
      NODPLC(LOC+13)=INDXX(NODE2,NODE6)
      NODPLC(LOC+14)=INDXX(NODE3,NODE6)
      NODPLC(LOC+15)=INDXX(NODE4,NODE2)
      NODPLC(LOC+16)=INDXX(NODE4,NODE5)
      NODPLC(LOC+17)=INDXX(NODE4,NODE6)
      NODPLC(LOC+18)=INDXX(NODE5,NODE1)
      NODPLC(LOC+19)=INDXX(NODE5,NODE2)
      NODPLC(LOC+20)=INDXX(NODE5,NODE4)
      NODPLC(LOC+21)=INDXX(NODE5,NODE6)
      NODPLC(LOC+22)=INDXX(NODE6,NODE2)
      NODPLC(LOC+23)=INDXX(NODE6,NODE3)
      NODPLC(LOC+24)=INDXX(NODE6,NODE4)
      NODPLC(LOC+25)=INDXX(NODE6,NODE5)
      NODPLC(LOC+27)=INDXX(NODE1,NODE1)
      NODPLC(LOC+28)=INDXX(NODE2,NODE2)
      NODPLC(LOC+29)=INDXX(NODE3,NODE3)
      NODPLC(LOC+30)=INDXX(NODE4,NODE4)
      NODPLC(LOC+31)=INDXX(NODE5,NODE5)
      NODPLC(LOC+32)=INDXX(NODE6,NODE6)
      LOC=NODPLC(LOC)
      GO TO 870
C
C  TRANSMISSION LINES
C
  900 LOC=LOCATE(17)
  910 IF ((LOC.EQ.0).OR.(NODPLC(LOC+33).NE.0)) GO TO 1000
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      NODE3=NODPLC(LOC+4)
      NODE4=NODPLC(LOC+5)
      NI1=NODPLC(LOC+6)
      NI2=NODPLC(LOC+7)
      IBR1=NODPLC(LOC+8)
      IBR2=NODPLC(LOC+9)
      NODPLC(LOC+10)=INDXX(NODE1,NODE1)
      NODPLC(LOC+11)=INDXX(NODE1,NI1)
      NODPLC(LOC+12)=INDXX(NODE2,IBR1)
      NODPLC(LOC+13)=INDXX(NODE3,NODE3)
      NODPLC(LOC+14)=INDXX(NODE4,IBR2)
      NODPLC(LOC+15)=INDXX(NI1,NODE1)
      NODPLC(LOC+16)=INDXX(NI1,NI1)
      NODPLC(LOC+17)=INDXX(NI1,IBR1)
      NODPLC(LOC+18)=INDXX(NI2,NI2)
      NODPLC(LOC+19)=INDXX(NI2,IBR2)
      NODPLC(LOC+20)=INDXX(IBR1,NODE2)
      NODPLC(LOC+21)=INDXX(IBR1,NODE3)
      NODPLC(LOC+22)=INDXX(IBR1,NODE4)
      NODPLC(LOC+23)=INDXX(IBR1,NI1)
      NODPLC(LOC+24)=INDXX(IBR1,IBR2)
      NODPLC(LOC+25)=INDXX(IBR2,NODE1)
      NODPLC(LOC+26)=INDXX(IBR2,NODE2)
      NODPLC(LOC+27)=INDXX(IBR2,NODE4)
      NODPLC(LOC+28)=INDXX(IBR2,NI2)
      NODPLC(LOC+29)=INDXX(IBR2,IBR1)
      NODPLC(LOC+31)=INDXX(NODE3,NI2)
      NODPLC(LOC+32)=INDXX(NI2,NODE3)
      LOC=NODPLC(LOC)
      GO TO 910
C
C  FINISHED
C
 1000 RETURN
      END
      SUBROUTINE CODGEN
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     THIS ROUTINE GENERATES MACHINE INSTRUCTIONS (FOR THE CDC 6400) TO
C LU-FACTOR AND SOLVE THE SET OF CIRCUIT EQUATIONS.
C
C SPICE VERSION 2G.6  SCCSID=TABINF 3/15/83
      COMMON /TABINF/ IELMNT,ISBCKT,NSBCKT,IUNSAT,NUNSAT,ITEMPS,NUMTEM,
     1   ISENS,NSENS,IFOUR,NFOUR,IFIELD,ICODE,IDELIM,ICOLUM,INSIZE,
     2   JUNODE,LSBKPT,NUMBKP,IORDER,JMNODE,IUR,IUC,ILC,ILR,NUMOFF,ISR,
     3   NMOFFC,ISEQ,ISEQ1,NEQN,NODEVS,NDIAG,ISWAP,IEQUA,MACINS,LVNIM1,
     4   LX0,LVN,LYNL,LYU,LYL,LX1,LX2,LX3,LX4,LX5,LX6,LX7,LD0,LD1,LTD,
     5   IMYNL,IMVN,LCVN,NSNOD,NSMAT,NSVAL,ICNOD,ICMAT,ICVAL,
     6   LOUTPT,LPOL,LZER,IRSWPF,IRSWPR,ICSWPF,ICSWPR,IRPT,JCPT,
     7   IROWNO,JCOLNO,NTTBR,NTTAR,LVNTMP
C SPICE VERSION 2G.6  SCCSID=CIRDAT 3/15/83
      COMMON /CIRDAT/ LOCATE(50),JELCNT(50),NUNODS,NCNODS,NUMNOD,NSTOP,
     1   NUT,NLT,NXTRM,NDIST,NTLIN,IBR,NUMVS,NUMALT,NUMCYC
C SPICE VERSION 2G.6  SCCSID=FLAGS 3/15/83
      COMMON /FLAGS/ IPRNTA,IPRNTL,IPRNTM,IPRNTN,IPRNTO,LIMTIM,LIMPTS,
     1   LVLCOD,LVLTIM,ITL1,ITL2,ITL3,ITL4,ITL5,ITL6,IGOOF,NOGO,KEOF
C SPICE VERSION 2G.6  SCCSID=KNSTNT 3/15/83
      COMMON /KNSTNT/ TWOPI,XLOG2,XLOG10,ROOT2,RAD,BOLTZ,CHARGE,CTOK,
     1   GMIN,RELTOL,ABSTOL,VNTOL,TRTOL,CHGTOL,EPS0,EPSSIL,EPSOX,
     2   PIVTOL,PIVREL
C SPICE VERSION 2G.6  SCCSID=MISCEL 3/15/83
      COMMON /MISCEL/ ATIME,APROG(3),ADATE,ATITLE(10),DEFL,DEFW,DEFAD,
     1  DEFAS,RSTATS(50),IWIDTH,LWIDTH,NOPAGE
C SPICE VERSION 2G.6  SCCSID=BLANK 3/15/83
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(64)
      COMPLEX CVALUE(32)
      EQUIVALENCE (VALUE(1),NODPLC(1),CVALUE(1))
      LOGICAL MEMPTR
      RETURN
      END
      SUBROUTINE MATPTR
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     THIS ROUTINE (BY CALLS TO THE ROUTINE RESERVE) ESTABLISHES THE
C NONZERO-ELEMENT STRUCTURE OF THE CIRCUIT EQUATION COEFFICIENT MATRIX.
C
C SPICE VERSION 2G.6  SCCSID=TABINF 3/15/83
      COMMON /TABINF/ IELMNT,ISBCKT,NSBCKT,IUNSAT,NUNSAT,ITEMPS,NUMTEM,
     1   ISENS,NSENS,IFOUR,NFOUR,IFIELD,ICODE,IDELIM,ICOLUM,INSIZE,
     2   JUNODE,LSBKPT,NUMBKP,IORDER,JMNODE,IUR,IUC,ILC,ILR,NUMOFF,ISR,
     3   NMOFFC,ISEQ,ISEQ1,NEQN,NODEVS,NDIAG,ISWAP,IEQUA,MACINS,LVNIM1,
     4   LX0,LVN,LYNL,LYU,LYL,LX1,LX2,LX3,LX4,LX5,LX6,LX7,LD0,LD1,LTD,
     5   IMYNL,IMVN,LCVN,NSNOD,NSMAT,NSVAL,ICNOD,ICMAT,ICVAL,
     6   LOUTPT,LPOL,LZER,IRSWPF,IRSWPR,ICSWPF,ICSWPR,IRPT,JCPT,
     7   IROWNO,JCOLNO,NTTBR,NTTAR,LVNTMP
C SPICE VERSION 2G.6  SCCSID=CIRDAT 3/15/83
      COMMON /CIRDAT/ LOCATE(50),JELCNT(50),NUNODS,NCNODS,NUMNOD,NSTOP,
     1   NUT,NLT,NXTRM,NDIST,NTLIN,IBR,NUMVS,NUMALT,NUMCYC
C SPICE VERSION 2G.6  SCCSID=BLANK 3/15/83
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(64)
      COMPLEX CVALUE(32)
      EQUIVALENCE (VALUE(1),NODPLC(1),CVALUE(1))
C
C  ALLOCATE AND INITIALIZE STORAGE
C
      CALL GETM4(ISR,NSTOP+1)
      NUMVS=JELCNT(3)+JELCNT(6)+JELCNT(8)+JELCNT(9)+2*JELCNT(17)
      CALL GETM4(ISEQ,NUMVS)
      CALL GETM4(ISEQ1,NUMVS)
      CALL GETM4(NEQN,NUMVS)
      CALL GETM4(NODEVS,NUMNOD)
      CALL GETM4(NDIAG,NSTOP)
      CALL GETM4(NMOFFC,NSTOP)
      CALL GETM4(NUMOFF,NSTOP)
      CALL GETM4(IRPT,NSTOP)
      CALL GETM4(JCPT,NSTOP)
      CALL GETM4(IROWNO,NSTOP)
      CALL GETM4(JCOLNO,NSTOP)
      CALL SLPMEM(IRPT,NSTOP)
      CALL SLPMEM(JCPT,NSTOP)
      CALL SLPMEM(IROWNO,NSTOP)
      CALL SLPMEM(JCOLNO,NSTOP)
      CALL CRUNCH
C
      CALL ZERO4(NODPLC(IRPT+1),NSTOP)
      CALL ZERO4(NODPLC(JCPT+1),NSTOP)
      CALL ZERO4(NODPLC(IROWNO+1),NSTOP)
      CALL ZERO4(NODPLC(JCOLNO+1),NSTOP)
      CALL ZERO4(NODPLC(ISEQ1+1),NUMVS)
      CALL ZERO4(NODPLC(NODEVS+1),NUMNOD)
      CALL ZERO4(NODPLC(NDIAG+1),NSTOP)
      CALL ZERO4(NODPLC(NMOFFC+1),NSTOP)
      CALL ZERO4(NODPLC(NUMOFF+1),NSTOP)
C
      NUMVS=0
      NXTRM=0
      NDIST=0
      NTLIN=1
      IBR=NUMNOD
C
C  RESISTORS
C
      LOC=LOCATE(1)
  110 IF ((LOC.EQ.0).OR.(NODPLC(LOC+8).NE.0)) GO TO 120
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      CALL RESERV(NODE1,NODE1)
      CALL RESERV(NODE1,NODE2)
      CALL RESERV(NODE2,NODE1)
      CALL RESERV(NODE2,NODE2)
      LOC=NODPLC(LOC)
      GO TO 110
C
C  CAPACITORS
C
  120 LOC=LOCATE(2)
  130 IF ((LOC.EQ.0).OR.(NODPLC(LOC+12).NE.0)) GO TO 400
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      CALL RESERV(NODE1,NODE2)
      CALL RESERV(NODE2,NODE1)
      NTEMP=NODPLC(NDIAG+NODE1)
      CALL RESERV(NODE1,NODE1)
      NODPLC(NDIAG+NODE1)=NTEMP
      NTEMP=NODPLC(NDIAG+NODE2)
      CALL RESERV(NODE2,NODE2)
      NODPLC(NDIAG+NODE2)=NTEMP
      NODPLC(LOC+8)=NXTRM+1
      NXTRM=NXTRM+2
      LOC=NODPLC(LOC)
      GO TO 130
C
C  INDUCTORS
C
  400 LOC=LOCATE(3)
  430 IF ((LOC.EQ.0).OR.(NODPLC(LOC+14).NE.0)) GO TO 440
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      IBR=IBR+1
      NODPLC(LOC+5)=IBR
      CALL RESERV(NODE1,IBR)
      CALL RESERV(NODE2,IBR)
      CALL RESERV(IBR,NODE1)
      CALL RESERV(IBR,NODE2)
      NTEMP=NODPLC(NDIAG+IBR)
      CALL RESERV(IBR,IBR)
      NODPLC(NDIAG+IBR)=NTEMP
      NUMVS=NUMVS+1
      NODPLC(ISEQ+NUMVS)=LOC
      NODPLC(NEQN+NUMVS)=IBR
      NODPLC(NODEVS+NODE1)=NODPLC(NODEVS+NODE1)+1
      NODPLC(NODEVS+NODE2)=NODPLC(NODEVS+NODE2)+1
      NODPLC(LOC+11)=NXTRM+1
      NXTRM=NXTRM+2
      LOC=NODPLC(LOC)
      GO TO 430
C
C  MUTUAL INDUCTORS
C
  440 LOC=LOCATE(4)
  450 IF ((LOC.EQ.0).OR.(NODPLC(LOC+6).NE.0)) GO TO 460
      NL1=NODPLC(LOC+2)
      NL2=NODPLC(LOC+3)
      NL1=NODPLC(NL1+5)
      NL2=NODPLC(NL2+5)
      CALL RESERV(NL1,NL2)
      CALL RESERV(NL2,NL1)
      LOC=NODPLC(LOC)
      GO TO 450
C
C  NONLINEAR VOLTAGE-CONTROLLED CURRENT SOURCES
C
  460 LOC=LOCATE(5)
  462 IF ((LOC.EQ.0).OR.(NODPLC(LOC+13).NE.0)) GO TO 464
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      NDIM=NODPLC(LOC+4)
      NDIM2=NDIM+NDIM
      LOCN=NODPLC(LOC+6)
      DO 463 I=1,NDIM2
      NODE=NODPLC(LOCN+I)
      CALL RESERV(NODE1,NODE)
      CALL RESERV(NODE2,NODE)
  463 CONTINUE
      NODPLC(LOC+12)=NXTRM+1
      NXTRM=NXTRM+1+NDIM2
      LOC=NODPLC(LOC)
      GO TO 462
C
C  NONLINEAR VOLTAGE CONTROLLED VOLTAGE SOURCES
C
  464 LOC=LOCATE(6)
  466 IF ((LOC.EQ.0).OR.(NODPLC(LOC+14).NE.0)) GO TO 468
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      IBR=IBR+1
      NODPLC(LOC+6)=IBR
      CALL RESERV(NODE1,IBR)
      CALL RESERV(NODE2,IBR)
      CALL RESERV(IBR,NODE1)
      CALL RESERV(IBR,NODE2)
      NUMVS=NUMVS+1
      NODPLC(ISEQ+NUMVS)=LOC
      NODPLC(NEQN+NUMVS)=IBR
      NODPLC(NODEVS+NODE1)=NODPLC(NODEVS+NODE1)+1
      NODPLC(NODEVS+NODE2)=NODPLC(NODEVS+NODE2)+1
      NDIM=NODPLC(LOC+4)
      NDIM2=NDIM+NDIM
      LOCN=NODPLC(LOC+7)
      DO 467 I=1,NDIM2
      NODE=NODPLC(LOCN+I)
      CALL RESERV(IBR,NODE)
  467 CONTINUE
      NODPLC(LOC+13)=NXTRM+1
      NXTRM=NXTRM+2+NDIM2
      LOC=NODPLC(LOC)
      GO TO 466
C
C  VOLTAGE SOURCES
C
  468 LOC=LOCATE(9)
  470 IF ((LOC.EQ.0).OR.(NODPLC(LOC+11).NE.0)) GO TO 472
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      IBR=IBR+1
      NODPLC(LOC+6)=IBR
      CALL RESERV(NODE1,IBR)
      CALL RESERV(NODE2,IBR)
      CALL RESERV(IBR,NODE1)
      CALL RESERV(IBR,NODE2)
      NUMVS=NUMVS+1
      NODPLC(ISEQ+NUMVS)=LOC
      NODPLC(NEQN+NUMVS)=IBR
      NODPLC(NODEVS+NODE1)=NODPLC(NODEVS+NODE1)+1
      NODPLC(NODEVS+NODE2)=NODPLC(NODEVS+NODE2)+1
      LOC=NODPLC(LOC)
      GO TO 470
C
C  NONLINEAR CURRENT CONTROLLED CURRENT SOURCES
C
  472 LOC=LOCATE(7)
  474 IF ((LOC.EQ.0).OR.(NODPLC(LOC+13).NE.0)) GO TO 476
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      NDIM=NODPLC(LOC+4)
      LOCVS=NODPLC(LOC+6)
      DO 475 I=1,NDIM
      LOCVST=NODPLC(LOCVS+I)
      KBR=NODPLC(LOCVST+6)
      CALL RESERV(NODE1,KBR)
      CALL RESERV(NODE2,KBR)
  475 CONTINUE
      NODPLC(LOC+12)=NXTRM+1
      NXTRM=NXTRM+1+NDIM+NDIM
      LOC=NODPLC(LOC)
      GO TO 474
C
C  NONLINEAR CURRENT CONTROLLED VOLTAGE SOURCES
C
  476 LOC=LOCATE(8)
  478 IF ((LOC.EQ.0).OR.(NODPLC(LOC+14).NE.0)) GO TO 500
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      IBR=IBR+1
      NODPLC(LOC+6)=IBR
      CALL RESERV(NODE1,IBR)
      CALL RESERV(NODE2,IBR)
      CALL RESERV(IBR,NODE1)
      CALL RESERV(IBR,NODE2)
      NUMVS=NUMVS+1
      NODPLC(ISEQ+NUMVS)=LOC
      NODPLC(NEQN+NUMVS)=IBR
      NODPLC(NODEVS+NODE1)=NODPLC(NODEVS+NODE1)+1
      NODPLC(NODEVS+NODE2)=NODPLC(NODEVS+NODE2)+1
      NDIM=NODPLC(LOC+4)
      LOCVS=NODPLC(LOC+7)
      DO 479 I=1,NDIM
      LOCVST=NODPLC(LOCVS+I)
      KBR=NODPLC(LOCVST+6)
      CALL RESERV(IBR,KBR)
  479 CONTINUE
      NODPLC(LOC+13)=NXTRM+1
      NXTRM=NXTRM+2+NDIM+NDIM
      LOC=NODPLC(LOC)
      GO TO 478
C
C  DIODES
C
  500 LOC=LOCATE(11)
  510 IF ((LOC.EQ.0).OR.(NODPLC(LOC+16).NE.0)) GO TO 520
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      NODE3=NODPLC(LOC+4)
      CALL RESERV(NODE1,NODE1)
      CALL RESERV(NODE2,NODE2)
      CALL RESERV(NODE3,NODE3)
      CALL RESERV(NODE1,NODE3)
      CALL RESERV(NODE2,NODE3)
      CALL RESERV(NODE3,NODE1)
      CALL RESERV(NODE3,NODE2)
      NODPLC(LOC+11)=NXTRM+1
      NXTRM=NXTRM+5
      NODPLC(LOC+12)=NDIST+1
      NDIST=NDIST+7
      LOC=NODPLC(LOC)
      GO TO 510
C
C  TRANSISTORS
C
  520 LOC=LOCATE(12)
  530 IF ((LOC.EQ.0).OR.(NODPLC(LOC+36).NE.0)) GO TO 540
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      NODE3=NODPLC(LOC+4)
      NODE4=NODPLC(LOC+5)
      NODE5=NODPLC(LOC+6)
      NODE6=NODPLC(LOC+7)
      NODE7=NODPLC(LOC+30)
      LOCM=NODPLC(LOC+8)
      LOCM=NODPLC(LOCM+1)
      CDIS=VALUE(LOCM+32)
      CALL RESERV(NODE1,NODE1)
      CALL RESERV(NODE2,NODE2)
      CALL RESERV(NODE3,NODE3)
      CALL RESERV(NODE4,NODE4)
      CALL RESERV(NODE5,NODE5)
      CALL RESERV(NODE6,NODE6)
      CALL RESERV(NODE1,NODE4)
      CALL RESERV(NODE2,NODE5)
      CALL RESERV(NODE3,NODE6)
      CALL RESERV(NODE4,NODE5)
      CALL RESERV(NODE4,NODE6)
      CALL RESERV(NODE5,NODE6)
      CALL RESERV(NODE4,NODE1)
      CALL RESERV(NODE5,NODE2)
      CALL RESERV(NODE6,NODE3)
      CALL RESERV(NODE5,NODE4)
      CALL RESERV(NODE6,NODE4)
      CALL RESERV(NODE6,NODE5)
      CALL RESERV(NODE7,NODE7)
      CALL RESERV(NODE4,NODE7)
      CALL RESERV(NODE7,NODE4)
      IF (CDIS.LT.1.0D0) CALL RESERV(NODE2,NODE4)
      IF (CDIS.LT.1.0D0) CALL RESERV(NODE4,NODE2)
      NODPLC(LOC+22)=NXTRM+1
      NXTRM=NXTRM+19
      NODPLC(LOC+23)=NDIST+1
      NDIST=NDIST+21
      LOC=NODPLC(LOC)
      GO TO 530
C
C  JFETS
C
  540 LOC=LOCATE(13)
  550 IF ((LOC.EQ.0).OR.(NODPLC(LOC+25).NE.0)) GO TO 560
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      NODE3=NODPLC(LOC+4)
      NODE4=NODPLC(LOC+5)
      NODE5=NODPLC(LOC+6)
      CALL RESERV(NODE1,NODE1)
      CALL RESERV(NODE2,NODE2)
      CALL RESERV(NODE3,NODE3)
      CALL RESERV(NODE4,NODE4)
      CALL RESERV(NODE5,NODE5)
      CALL RESERV(NODE1,NODE4)
      CALL RESERV(NODE2,NODE4)
      CALL RESERV(NODE2,NODE5)
      CALL RESERV(NODE3,NODE5)
      CALL RESERV(NODE4,NODE5)
      CALL RESERV(NODE4,NODE1)
      CALL RESERV(NODE4,NODE2)
      CALL RESERV(NODE5,NODE2)
      CALL RESERV(NODE5,NODE3)
      CALL RESERV(NODE5,NODE4)
      NODPLC(LOC+19)=NXTRM+1
      NXTRM=NXTRM+13
      LOC=NODPLC(LOC)
      GO TO 550
C
C  MOSFETS
C
  560 LOC=LOCATE(14)
  570 IF ((LOC.EQ.0).OR.(NODPLC(LOC+33).NE.0)) GO TO 600
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      NODE3=NODPLC(LOC+4)
      NODE4=NODPLC(LOC+5)
      NODE5=NODPLC(LOC+6)
      NODE6=NODPLC(LOC+7)
      CALL RESERV(NODE1,NODE1)
      CALL RESERV(NODE2,NODE2)
      CALL RESERV(NODE3,NODE3)
      CALL RESERV(NODE4,NODE4)
      CALL RESERV(NODE5,NODE5)
      CALL RESERV(NODE6,NODE6)
      CALL RESERV(NODE1,NODE5)
      CALL RESERV(NODE2,NODE4)
      CALL RESERV(NODE2,NODE5)
      CALL RESERV(NODE2,NODE6)
      CALL RESERV(NODE3,NODE6)
      CALL RESERV(NODE4,NODE5)
      CALL RESERV(NODE4,NODE6)
      CALL RESERV(NODE5,NODE6)
      CALL RESERV(NODE5,NODE1)
      CALL RESERV(NODE4,NODE2)
      CALL RESERV(NODE5,NODE2)
      CALL RESERV(NODE6,NODE2)
      CALL RESERV(NODE6,NODE3)
      CALL RESERV(NODE5,NODE4)
      CALL RESERV(NODE6,NODE4)
      CALL RESERV(NODE6,NODE5)
      NODPLC(LOC+26)=NXTRM+1
      NXTRM=NXTRM+28
      LOC=NODPLC(LOC)
      GO TO 570
C
C  TRANSMISSION LINES
C
  600 LOC=LOCATE(17)
  610 IF ((LOC.EQ.0).OR.(NODPLC(LOC+33).NE.0)) GO TO 1000
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      NODE3=NODPLC(LOC+4)
      NODE4=NODPLC(LOC+5)
      NI1=NODPLC(LOC+6)
      NI2=NODPLC(LOC+7)
      IBR1=IBR+1
      IBR2=IBR+2
      IBR=IBR+2
      NODPLC(LOC+8)=IBR1
      NODPLC(LOC+9)=IBR2
      CALL RESERV(NODE1,NODE1)
      CALL RESERV(NODE1,NI1)
      CALL RESERV(NODE2,IBR1)
      CALL RESERV(NODE3,NODE3)
      CALL RESERV(NODE4,IBR2)
      CALL RESERV(NI1,NODE1)
      CALL RESERV(NI1,NI1)
      CALL RESERV(NI1,IBR1)
      CALL RESERV(NI2,NI2)
      CALL RESERV(NI2,IBR2)
      CALL RESERV(IBR1,NODE2)
      CALL RESERV(IBR1,NODE3)
      CALL RESERV(IBR1,NODE4)
      CALL RESERV(IBR1,NI1)
      CALL RESERV(IBR1,IBR2)
      CALL RESERV(IBR2,NODE1)
      CALL RESERV(IBR2,NODE2)
      CALL RESERV(IBR2,NODE4)
      CALL RESERV(IBR2,NI2)
      CALL RESERV(IBR2,IBR1)
      CALL RESERV(NODE3,NI2)
      CALL RESERV(NI2,NODE3)
      NUMVS=NUMVS+1
      NODPLC(ISEQ+NUMVS)=LOC
      NODPLC(ISEQ1+NUMVS)=1
      NODPLC(NEQN+NUMVS)=IBR1
      NODPLC(NODEVS+NI1)=NODPLC(NODEVS+NI1)+1
      NODPLC(NODEVS+NODE2)=NODPLC(NODEVS+NODE2)+1
      NUMVS=NUMVS+1
      NODPLC(ISEQ+NUMVS)=LOC
      NODPLC(ISEQ1+NUMVS)=2
      NODPLC(NEQN+NUMVS)=IBR2
      NODPLC(NODEVS+NI2)=NODPLC(NODEVS+NI2)+1
      NODPLC(NODEVS+NODE4)=NODPLC(NODEVS+NODE4)+1
      NODPLC(LOC+30)=NTLIN+1
      NTLIN=NTLIN+2
      LOC=NODPLC(LOC)
      GO TO 610
C
C  FINISHED
C
 1000 RETURN
      END
      SUBROUTINE REORDR
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     THIS ROUTINE SWAPS ROWS IN THE COEFFICIENT MATRIX TO ELIMINATE
C SINGULARITY PROBLEMS WHICH CAN BE RECOGNIZED BY EXAMINING THE CIRCUIT
C TOPOLOGY.
C
C SPICE VERSION 2G.6  SCCSID=TABINF 3/15/83
      COMMON /TABINF/ IELMNT,ISBCKT,NSBCKT,IUNSAT,NUNSAT,ITEMPS,NUMTEM,
     1   ISENS,NSENS,IFOUR,NFOUR,IFIELD,ICODE,IDELIM,ICOLUM,INSIZE,
     2   JUNODE,LSBKPT,NUMBKP,IORDER,JMNODE,IUR,IUC,ILC,ILR,NUMOFF,ISR,
     3   NMOFFC,ISEQ,ISEQ1,NEQN,NODEVS,NDIAG,ISWAP,IEQUA,MACINS,LVNIM1,
     4   LX0,LVN,LYNL,LYU,LYL,LX1,LX2,LX3,LX4,LX5,LX6,LX7,LD0,LD1,LTD,
     5   IMYNL,IMVN,LCVN,NSNOD,NSMAT,NSVAL,ICNOD,ICMAT,ICVAL,
     6   LOUTPT,LPOL,LZER,IRSWPF,IRSWPR,ICSWPF,ICSWPR,IRPT,JCPT,
     7   IROWNO,JCOLNO,NTTBR,NTTAR,LVNTMP
C SPICE VERSION 2G.6  SCCSID=CIRDAT 3/15/83
      COMMON /CIRDAT/ LOCATE(50),JELCNT(50),NUNODS,NCNODS,NUMNOD,NSTOP,
     1   NUT,NLT,NXTRM,NDIST,NTLIN,IBR,NUMVS,NUMALT,NUMCYC
C SPICE VERSION 2G.6  SCCSID=FLAGS 3/15/83
      COMMON /FLAGS/ IPRNTA,IPRNTL,IPRNTM,IPRNTN,IPRNTO,LIMTIM,LIMPTS,
     1   LVLCOD,LVLTIM,ITL1,ITL2,ITL3,ITL4,ITL5,ITL6,IGOOF,NOGO,KEOF
C SPICE VERSION 2G.6  SCCSID=BLANK 3/15/83
      COMMON /BLANK/ VALUE(200000)
C SPICE VERSION 2G.6  SCCSID=STATUS 3/15/83
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
      INTEGER NODPLC(64)
      COMPLEX CVALUE(32)
      EQUIVALENCE (VALUE(1),NODPLC(1),CVALUE(1))
C
C  ALLOCATE AND INITIALIZE STORAGE
C
      CALL GETM4(IRSWPF,NSTOP)
      CALL GETM4(IRSWPR,NSTOP)
      CALL GETM4(ICSWPF,NSTOP)
      CALL GETM4(ICSWPR,NSTOP)
C
      DO 10 I=1,NSTOP
      NODPLC(IRSWPF+I)=I
   10 CONTINUE
      CALL COPY4(NODPLC(IRSWPF+1),NODPLC(IRSWPR+1),NSTOP)
      CALL COPY4(NODPLC(IRSWPF+1),NODPLC(ICSWPF+1),NSTOP)
      CALL COPY4(NODPLC(IRSWPF+1),NODPLC(ICSWPR+1),NSTOP)
C
C  SWAP CURRENT EQUATIONS INTO ADMITTANCE PART OF EQUATION MATRIX
C
      NEXTV=1
C
C  FIND SUITABLE VOLTAGE SOURCE
C
  100 IF (NEXTV.GT.NUMVS) GO TO 600
      IX=0
      DO 130 I=NEXTV,NUMVS
      LOC=NODPLC(ISEQ+I)
      NODE=NODPLC(LOC+2)
      NFLAG=NODPLC(ISEQ1+I)
      IF (NFLAG.EQ.1) NODE=NODPLC(LOC+6)
      IF (NFLAG.EQ.2) NODE=NODPLC(LOC+7)
      IF (NODE.EQ.1) GO TO 110
      IF (NODPLC(NODEVS+NODE).GE.2) GO TO 110
      IF (NODPLC(NDIAG+NODE).EQ.0) GO TO 145
      IX=I
      LOCX=LOC
      NODEX=NODE
  110 NODE=NODPLC(LOC+3)
      IF (NFLAG.EQ.2) NODE=NODPLC(LOC+5)
      IF (NODE.EQ.1) GO TO 130
      IF (NODPLC(NODEVS+NODE).GE.2) GO TO 130
  120 IF (NODPLC(NDIAG+NODE).EQ.0) GO TO 145
      IX=I
      LOCX=LOC
      NODEX=NODE
  130 CONTINUE
      IF (IX.EQ.0) GO TO 590
      I=IX
      LOC=LOCX
      NODE=NODEX
C
C  RESEQUENCE VOLTAGE SOURCES
C
  145 NODPLC(ISEQ+I)=NODPLC(ISEQ+NEXTV)
      NODPLC(ISEQ+NEXTV)=LOC
      LTEMP=NODPLC(ISEQ1+I)
      NODPLC(ISEQ1+I)=NODPLC(ISEQ1+NEXTV)
      NODPLC(ISEQ1+NEXTV)=LTEMP
      IBR=NODPLC(NEQN+I)
      NODPLC(NEQN+I)=NODPLC(NEQN+NEXTV)
      NODPLC(NEQN+NEXTV)=IBR
      NODE1=NODPLC(LOC+2)
      IF (LTEMP.EQ.1) NODE1=NODPLC(LOC+6)
      IF (LTEMP.EQ.2) NODE1=NODPLC(LOC+7)
      NODE2=NODPLC(LOC+3)
      IF (LTEMP.EQ.1) NODE2=NODPLC(LOC+3)
      IF (LTEMP.EQ.2) NODE2=NODPLC(LOC+5)
      NODPLC(NODEVS+NODE1)=NODPLC(NODEVS+NODE1)-1
      NODPLC(NODEVS+NODE2)=NODPLC(NODEVS+NODE2)-1
C
C  SET ROW SWAP INDICATORS
C
      L=NODPLC(IRSWPF+IBR)
      J=NODPLC(IRSWPR+NODE)
      NODPLC(IRSWPF+J)=L
      NODPLC(IRSWPR+L)=J
      NODPLC(IRSWPF+IBR)=NODE
      NODPLC(IRSWPR+NODE)=IBR
      CALL SWAPIJ(IBR,J,1,1)
      NEXTV=NEXTV+1
      GO TO 100
C
C
C  ERROR - VOLTAGE-SOURCE/INDUCTOR/TRANSMISSION-LINE LOOP DETECTED ...
C
  590 NOGO=1
      WRITE (IOFILE,591)
C...  LOOP SHOULD HAVE BEEN DETECTED IN TOPCHK
  591 FORMAT('0*ABORT*:  SPICE INTERNAL ERROR IN REORDR'/)
C
C  FINISHED
C
  600 RETURN
      END
C SPICE VERSION 2G.6  SCCSID=dctran.ma 3/15/83
      SUBROUTINE ASOL
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     THIS ROUTINE EVALUATES THE ADJOINT CIRCUIT RESPONSE BY DOING A
C FORWARD/BACKWARD SUBSTITUTION ON THE TRANSPOSE OF THE COEFFICIENT
C MATRIX.
C
C SPICE VERSION 2G.6  SCCSID=TABINF 3/15/83
      COMMON /TABINF/ IELMNT,ISBCKT,NSBCKT,IUNSAT,NUNSAT,ITEMPS,NUMTEM,
     1   ISENS,NSENS,IFOUR,NFOUR,IFIELD,ICODE,IDELIM,ICOLUM,INSIZE,
     2   JUNODE,LSBKPT,NUMBKP,IORDER,JMNODE,IUR,IUC,ILC,ILR,NUMOFF,ISR,
     3   NMOFFC,ISEQ,ISEQ1,NEQN,NODEVS,NDIAG,ISWAP,IEQUA,MACINS,LVNIM1,
     4   LX0,LVN,LYNL,LYU,LYL,LX1,LX2,LX3,LX4,LX5,LX6,LX7,LD0,LD1,LTD,
     5   IMYNL,IMVN,LCVN,NSNOD,NSMAT,NSVAL,ICNOD,ICMAT,ICVAL,
     6   LOUTPT,LPOL,LZER,IRSWPF,IRSWPR,ICSWPF,ICSWPR,IRPT,JCPT,
     7   IROWNO,JCOLNO,NTTBR,NTTAR,LVNTMP
C SPICE VERSION 2G.6  SCCSID=CIRDAT 3/15/83
      COMMON /CIRDAT/ LOCATE(50),JELCNT(50),NUNODS,NCNODS,NUMNOD,NSTOP,
     1   NUT,NLT,NXTRM,NDIST,NTLIN,IBR,NUMVS,NUMALT,NUMCYC
C SPICE VERSION 2G.6  SCCSID=BLANK 3/15/83
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(64)
      COMPLEX CVALUE(32)
      EQUIVALENCE (VALUE(1),NODPLC(1),CVALUE(1))
C
C  FORWARD SUBSTITUTION
C
      DO 20 I=2,NSTOP
      IORD=NODPLC(ICSWPF+I)
      LOC=I
   10 LOC=NODPLC(IRPT+LOC)
      IF (NODPLC(IROWNO+LOC).GE.I) GO TO 15
      J=NODPLC(IROWNO+LOC)
      JORD=NODPLC(ICSWPF+J)
      VALUE(LVN+IORD)=VALUE(LVN+IORD)-VALUE(LVN+LOC)*VALUE(LVN+JORD)
      GO TO 10
   15 JORD=NODPLC(IRSWPF+I)
      LOCNN=INDXX(JORD,IORD)
      VALUE(LVN+IORD)=VALUE(LVN+IORD)/VALUE(LVN+LOCNN)
   20 CONTINUE
C
C  BACKWARD SUBSTITUTION
C
      I=NSTOP
   30 I=I-1
      IF (I.LE.1) GO TO 60
      IORD=NODPLC(ICSWPF+I)
      LOC=I
   35 LOC=NODPLC(IRPT+LOC)
   40 IF (NODPLC(IROWNO+LOC).NE.I) GO TO 35
   50 LOC=NODPLC(IRPT+LOC)
      IF (LOC.EQ.0) GO TO 30
      J=NODPLC(IROWNO+LOC)
      JORD=NODPLC(ICSWPF+J)
      VALUE(LVN+IORD)=VALUE(LVN+IORD)-VALUE(LVN+LOC)*VALUE(LVN+JORD)
      GO TO 50
C
C     REORDER SOLUTION VECTOR
C
   60 DO 70 I=1,NSTOP
      J=NODPLC(IRSWPR+I)
      K=NODPLC(ICSWPF+J)
      VALUE(LVNTMP+I)=VALUE(LVN+K)
   70 CONTINUE
      CALL COPY8(VALUE(LVNTMP+1),VALUE(LVN+1),NSTOP)
C
C  FINISHED
C
      RETURN
      END
C SPICE VERSION 2G.6  SCCSID=acan.ma 3/15/83
      SUBROUTINE ACAN
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      REAL T1,T2
C
C     THIS ROUTINE DRIVES THE SMALL-SIGNAL ANALYSES.
C
C SPICE VERSION 2G.6  SCCSID=TABINF 3/15/83
      COMMON /TABINF/ IELMNT,ISBCKT,NSBCKT,IUNSAT,NUNSAT,ITEMPS,NUMTEM,
     1   ISENS,NSENS,IFOUR,NFOUR,IFIELD,ICODE,IDELIM,ICOLUM,INSIZE,
     2   JUNODE,LSBKPT,NUMBKP,IORDER,JMNODE,IUR,IUC,ILC,ILR,NUMOFF,ISR,
     3   NMOFFC,ISEQ,ISEQ1,NEQN,NODEVS,NDIAG,ISWAP,IEQUA,MACINS,LVNIM1,
     4   LX0,LVN,LYNL,LYU,LYL,LX1,LX2,LX3,LX4,LX5,LX6,LX7,LD0,LD1,LTD,
     5   IMYNL,IMVN,LCVN,NSNOD,NSMAT,NSVAL,ICNOD,ICMAT,ICVAL,
     6   LOUTPT,LPOL,LZER,IRSWPF,IRSWPR,ICSWPF,ICSWPR,IRPT,JCPT,
     7   IROWNO,JCOLNO,NTTBR,NTTAR,LVNTMP
C SPICE VERSION 2G.6  SCCSID=MISCEL 3/15/83
      COMMON /MISCEL/ ATIME,APROG(3),ADATE,ATITLE(10),DEFL,DEFW,DEFAD,
     1  DEFAS,RSTATS(50),IWIDTH,LWIDTH,NOPAGE
C SPICE VERSION 2G.6  SCCSID=CIRDAT 3/15/83
      COMMON /CIRDAT/ LOCATE(50),JELCNT(50),NUNODS,NCNODS,NUMNOD,NSTOP,
     1   NUT,NLT,NXTRM,NDIST,NTLIN,IBR,NUMVS,NUMALT,NUMCYC
C SPICE VERSION 2G.6  SCCSID=STATUS 3/15/83
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
C SPICE VERSION 2G.6  SCCSID=FLAGS 3/15/83
      COMMON /FLAGS/ IPRNTA,IPRNTL,IPRNTM,IPRNTN,IPRNTO,LIMTIM,LIMPTS,
     1   LVLCOD,LVLTIM,ITL1,ITL2,ITL3,ITL4,ITL5,ITL6,IGOOF,NOGO,KEOF
C SPICE VERSION 2G.6  SCCSID=KNSTNT 3/15/83
      COMMON /KNSTNT/ TWOPI,XLOG2,XLOG10,ROOT2,RAD,BOLTZ,CHARGE,CTOK,
     1   GMIN,RELTOL,ABSTOL,VNTOL,TRTOL,CHGTOL,EPS0,EPSSIL,EPSOX,
     2   PIVTOL,PIVREL
C SPICE VERSION 2G.6  SCCSID=AC 3/15/83
      COMMON /AC/ FSTART,FSTOP,FINCR,SKW2,REFPRL,SPW2,JACFLG,IDFREQ,
     1   INOISE,NOSPRT,NOSOUT,NOSIN,IDIST,IDPRT
C SPICE VERSION 2G.6  SCCSID=CJE 3/15/83
      COMMON /CJE/ MAXTIM,ITIME,ICOST
C SPICE VERSION 2G.6  SCCSID=BLANK 3/15/83
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(64)
      COMPLEX CVALUE(32)
      COMPLEX CENDOR
      EQUIVALENCE (VALUE(1),NODPLC(1),CVALUE(1))
      CALL SECOND(T1)
C.. POST-PROCESSOR INITIALIZATION
      IF(IPOSTP.EQ.0) GO TO 1
      NUMCUR=JELCNT(9)
      NUMPOS=NUNODS+NUMCUR
      CALL GETM16(IBUFF,NUMPOS)
      NUMPOS=NUMPOS*4
      IF(NUMCUR.EQ.0) GO TO 1
      LOC=LOCATE(9)
      LOCCUR=NODPLC(LOC+6)-1
C
C  ALLOCATE STORAGE
C
    1 CALL GETM8(NDIAG,2*NSTOP)
      CALL GETM8(LVN,NSTOP+NTTBR)
      CALL GETM8(IMVN,NSTOP+NTTBR)
      CALL GETM16(LCVN,NSTOP)
      IF (IDIST.NE.0) CALL DINIT
      NANDD=0
      IF (INOISE.EQ.0) GO TO 10
      IF (IDIST.EQ.0) GO TO 10
      NANDD=1
      CALL GETM16(LVNTMP,NSTOP)
   10 CALL GETM16(LOUTPT,0)
      CALL CRUNCH
      NUMOUT=JELCNT(43)+JELCNT(44)+JELCNT(45)+1
      LYNL=LVN
      IMYNL=IMVN
      LCVNTP=LVNTMP
      ICALC=0
      IF (IPOSTP.NE.0) CALL PHEADR(ATITLE)
      FREQ=FSTART
C
C  LOAD Y MATRIX AND C VECTOR, SOLVE FOR V VECTOR
C
  100 CALL GETCJE
      IF ((MAXTIM-ITIME).LE.LIMTIM) GO TO 900
      OMEGA=TWOPI*FREQ
      CALL ACLOAD
  110 CALL ACDCMP
      CALL ACSOL
      IF (IGOOF.EQ.0) GO TO 200
      WRITE (IOFILE,121) IGOOF,FREQ
  121 FORMAT('0WARNING:  UNDERFLOW ',I4,' TIME(S) IN AC ANALYSIS AT FREQ
     1 = ',1PD9.3,' HZ')
      IGOOF=0
C
C  STORE OUTPUTS
C
  200 CALL EXTMEM(LOUTPT,NUMOUT)
      LOCO=LOUTPT+ICALC*NUMOUT
      ICALC=ICALC+1
      CVALUE(LOCO+1)=CMPLX(SNGL(FREQ),SNGL(OMEGA))
      LOC=LOCATE(43)
  310 IF (LOC.EQ.0) GO TO 350
      IF (NODPLC(LOC+5).NE.0) GO TO 320
      NODE1=NODPLC(LOC+2)
      NODE2=NODPLC(LOC+3)
      ISEQ=NODPLC(LOC+4)
      CVALUE(LOCO+ISEQ)=CVALUE(LCVN+NODE1)-CVALUE(LCVN+NODE2)
      LOC=NODPLC(LOC)
      GO TO 310
  320 IPTR=NODPLC(LOC+2)
      IPTR=NODPLC(IPTR+6)
      ISEQ=NODPLC(LOC+4)
      CVALUE(LOCO+ISEQ)=CVALUE(LCVN+IPTR)
      LOC=NODPLC(LOC)
      GO TO 310
  350 IF(IPOSTP.EQ.0) GO TO 400
      CVALUE(IBUFF+1)=CMPLX(SNGL(FREQ),0.0E0)
      CALL COPY16(CVALUE(LCVN+2),CVALUE(IBUFF+2),NUNODS-1)
      IF(NUMCUR.NE.0) CALL COPY16(CVALUE(LCVN+LOCCUR+1),
     1  CVALUE(IBUFF+NUNODS+1),NUMCUR)
      CALL DBLSGL(CVALUE(IBUFF+1),NUMPOS)
      CALL FWRITE(CVALUE(IBUFF+1),NUMPOS)
C
C  NOISE AND DISTORTION ANALYSES
C
  400 IF (NANDD.EQ.0) GO TO 410
      CALL COPY16(CVALUE(LCVN+1),CVALUE(LCVNTP+1),NSTOP)
  410 IF (INOISE.NE.0) CALL NOISE(LOCO)
      IF (NANDD.EQ.0) GO TO 420
      CALL COPY16(CVALUE(LCVNTP+1),CVALUE(LCVN+1),NSTOP)
  420 IF (IDIST.NE.0) CALL DISTO(LOCO)
C
C  INCREMENT FREQUENCY
C
      IF (ICALC.GE.JACFLG) GO TO 1000
      IF (IDFREQ.GE.3) GO TO 510
      FREQ=FREQ*FINCR
      GO TO 100
  510 FREQ=FREQ+FINCR
      GO TO 100
C
C  FINISHED
C
  900 WRITE (IOFILE,901)
  901 FORMAT('0*ERROR*:  CPU TIME LIMIT EXCEEDED ... ANALYSIS STOPPED'/)
      NOGO=1
 1000 IF(IPOSTP.EQ.0) GO TO 1010
      IF (IPOSTP.NE.0) CALL CLSRAW
      IF(IPOSTP.NE.0) CALL CLRMEM(IBUFF)
 1010 CALL CLRMEM(LVNIM1)
      CALL CLRMEM(LX0)
      CALL CLRMEM(LVN)
      CALL CLRMEM(IMVN)
      CALL CLRMEM(LCVN)
      CALL CLRMEM(NDIAG)
      IF (IDIST.EQ.0) GO TO 1020
      CALL CLRMEM(LD0)
      CALL CLRMEM(LD1)
 1020 IF (NANDD.EQ.0) GO TO 1040
      CALL CLRMEM(LVNTMP)
 1040 CALL SECOND(T2)
      RSTATS(7)=RSTATS(7)+T2-T1
      RSTATS(8)=RSTATS(8)+ICALC
      RETURN
      END
      SUBROUTINE CDIV(XR,XI,YR,YI,CR,CI)
C.. OK IF CR AND CI ARE REALLY XR AND XI OR YR AND YI
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      XRTEMP=XR
      XITEMP=XI
      YRTEMP=YR
      YITEMP=YI
      AMAG2=YRTEMP*YRTEMP+YITEMP*YITEMP
      CR=(XRTEMP*YRTEMP+XITEMP*YITEMP)/AMAG2
      CI=(XITEMP*YRTEMP-XRTEMP*YITEMP)/AMAG2
      RETURN
      END
      SUBROUTINE CMULT(XR,XI,YR,YI,CR,CI)
C.. OK IF CR AND CI ARE REALLY XR AND XI OR YR AND YI
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      XRTEMP=XR
      XITEMP=XI
      YRTEMP=YR
      YITEMP=YI
      CR=XRTEMP*YRTEMP-XITEMP*YITEMP
      CI=XITEMP*YRTEMP+XRTEMP*YITEMP
      RETURN
      END
      SUBROUTINE ACDCMP
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     THIS ROUTINE PERFORMS AN LU FACTORIZATION OF THE CIRCUIT EQUATION
C COEFFICIENT MATRIX.
C
C SPICE VERSION 2G.6  SCCSID=TABINF 3/15/83
      COMMON /TABINF/ IELMNT,ISBCKT,NSBCKT,IUNSAT,NUNSAT,ITEMPS,NUMTEM,
     1   ISENS,NSENS,IFOUR,NFOUR,IFIELD,ICODE,IDELIM,ICOLUM,INSIZE,
     2   JUNODE,LSBKPT,NUMBKP,IORDER,JMNODE,IUR,IUC,ILC,ILR,NUMOFF,ISR,
     3   NMOFFC,ISEQ,ISEQ1,NEQN,NODEVS,NDIAG,ISWAP,IEQUA,MACINS,LVNIM1,
     4   LX0,LVN,LYNL,LYU,LYL,LX1,LX2,LX3,LX4,LX5,LX6,LX7,LD0,LD1,LTD,
     5   IMYNL,IMVN,LCVN,NSNOD,NSMAT,NSVAL,ICNOD,ICMAT,ICVAL,
     6   LOUTPT,LPOL,LZER,IRSWPF,IRSWPR,ICSWPF,ICSWPR,IRPT,JCPT,
     7   IROWNO,JCOLNO,NTTBR,NTTAR,LVNTMP
C SPICE VERSION 2G.6  SCCSID=CIRDAT 3/15/83
      COMMON /CIRDAT/ LOCATE(50),JELCNT(50),NUNODS,NCNODS,NUMNOD,NSTOP,
     1   NUT,NLT,NXTRM,NDIST,NTLIN,IBR,NUMVS,NUMALT,NUMCYC
C SPICE VERSION 2G.6  SCCSID=FLAGS 3/15/83
      COMMON /FLAGS/ IPRNTA,IPRNTL,IPRNTM,IPRNTN,IPRNTO,LIMTIM,LIMPTS,
     1   LVLCOD,LVLTIM,ITL1,ITL2,ITL3,ITL4,ITL5,ITL6,IGOOF,NOGO,KEOF
C SPICE VERSION 2G.6  SCCSID=KNSTNT 3/15/83
      COMMON /KNSTNT/ TWOPI,XLOG2,XLOG10,ROOT2,RAD,BOLTZ,CHARGE,CTOK,
     1   GMIN,RELTOL,ABSTOL,VNTOL,TRTOL,CHGTOL,EPS0,EPSSIL,EPSOX,
     2   PIVTOL,PIVREL
C SPICE VERSION 2G.6  SCCSID=BLANK 3/15/83
      COMMON /BLANK/ VALUE(200000)
C SPICE VERSION 2G.6  SCCSID=STATUS 3/15/83
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
      INTEGER NODPLC(64)
      COMPLEX CVALUE(32)
      EQUIVALENCE (VALUE(1),NODPLC(1),CVALUE(1))
C
      N=1
   10 N=N+1
      NXTI=N
      NXTJ=N
C
C     CALCULATE CONTRIBUTION FROM (NXTI,NXTJ)
C
      IF (N.GE.NSTOP) RETURN
      N1=NODPLC(IRSWPF+NXTI)
      N2=NODPLC(ICSWPF+NXTJ)
      LOCNN=INDXX(N1,N2)
      GDIAG=DABS(VALUE(LYNL+LOCNN))+DABS(VALUE(IMYNL+LOCNN))
      IF (GDIAG.GE.PIVTOL) GO TO 20
      VALUE(LYNL+LOCNN)=PIVTOL
      VALUE(IMYNL+LOCNN)=0.0D0
      WRITE(IOFILE,11) N
   11 FORMAT(1H0,' UNDERFLOW OCCURED AT STEP N= ',I5)
C
C     DOWN COL J
C
   20 LOCR=NODPLC(IRPT+LOCNN)
   25 IF (LOCR.EQ.0) GO TO 10
      I=NODPLC(IROWNO+LOCR)
      CALL CDIV(VALUE(LYNL+LOCR),VALUE(IMYNL+LOCR),VALUE(LYNL+LOCNN),
     1     VALUE(IMYNL+LOCNN),VALUE(LYNL+LOCR),VALUE(IMYNL+LOCR))
      LOCC=NODPLC(JCPT+LOCNN)
C
C     FOR EACH ELEMENT LOOK UP ROW NXTI
C
   30 IF (LOCC.EQ.0) GO TO 70
      J=NODPLC(JCOLNO+LOCC)
C
C     LOCATE ELEMENT (I,J)
C
   35 IF (J.LT.I) GO TO 45
      LOCIJ=LOCC
   40 LOCIJ=NODPLC(IRPT+LOCIJ)
      IF (NODPLC(IROWNO+LOCIJ).EQ.I) GO TO 55
      GO TO 40
   45 LOCIJ=LOCR
   50 LOCIJ=NODPLC(JCPT+LOCIJ)
      IF (NODPLC(JCOLNO+LOCIJ).EQ.J) GO TO 55
      GO TO 50
   55 CALL CMULT(VALUE(LYNL+LOCC),VALUE(IMYNL+LOCC),
     1     VALUE(LYNL+LOCR),VALUE(IMYNL+LOCR),XREAL,XIMAG)
      VALUE(LYNL+LOCIJ)=VALUE(LYNL+LOCIJ)-XREAL
      VALUE(IMYNL+LOCIJ)=VALUE(IMYNL+LOCIJ)-XIMAG
      LOCC=NODPLC(JCPT+LOCC)
      GO TO 30
   70 LOCR=NODPLC(IRPT+LOCR)
      GO TO 25
      END
      SUBROUTINE ACSOL
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     THIS ROUTINE SOLVES THE CIRCUIT EQUATIONS BY PERFORMING A FORWARD
C AND BACKWARD SUBSTITUTION USING THE PREVIOUSLY-COMPUTED LU FACTORS.
C
C SPICE VERSION 2G.6  SCCSID=TABINF 3/15/83
      COMMON /TABINF/ IELMNT,ISBCKT,NSBCKT,IUNSAT,NUNSAT,ITEMPS,NUMTEM,
     1   ISENS,NSENS,IFOUR,NFOUR,IFIELD,ICODE,IDELIM,ICOLUM,INSIZE,
     2   JUNODE,LSBKPT,NUMBKP,IORDER,JMNODE,IUR,IUC,ILC,ILR,NUMOFF,ISR,
     3   NMOFFC,ISEQ,ISEQ1,NEQN,NODEVS,NDIAG,ISWAP,IEQUA,MACINS,LVNIM1,
     4   LX0,LVN,LYNL,LYU,LYL,LX1,LX2,LX3,LX4,LX5,LX6,LX7,LD0,LD1,LTD,
     5   IMYNL,IMVN,LCVN,NSNOD,NSMAT,NSVAL,ICNOD,ICMAT,ICVAL,
     6   LOUTPT,LPOL,LZER,IRSWPF,IRSWPR,ICSWPF,ICSWPR,IRPT,JCPT,
     7   IROWNO,JCOLNO,NTTBR,NTTAR,LVNTMP
C SPICE VERSION 2G.6  SCCSID=CIRDAT 3/15/83
      COMMON /CIRDAT/ LOCATE(50),JELCNT(50),NUNODS,NCNODS,NUMNOD,NSTOP,
     1   NUT,NLT,NXTRM,NDIST,NTLIN,IBR,NUMVS,NUMALT,NUMCYC
C SPICE VERSION 2G.6  SCCSID=BLANK 3/15/83
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(64)
      COMPLEX CVALUE(32)
      EQUIVALENCE (VALUE(1),NODPLC(1),CVALUE(1))
C
C  FORWARD SUBSTITUTION
C
      DO 20 I=2,NSTOP
      LOC=I
      IORD=NODPLC(IRSWPF+I)
   10 LOC=NODPLC(JCPT+LOC)
      IF (NODPLC(JCOLNO+LOC).GE.I) GO TO 20
      J=NODPLC(JCOLNO+LOC)
      JORD=NODPLC(IRSWPF+J)
      CALL CMULT(VALUE(LYNL+LOC),VALUE(IMYNL+LOC),
     1     VALUE(LVN+JORD),VALUE(IMVN+JORD),XREAL,XIMAG)
      VALUE(LVN+IORD)=VALUE(LVN+IORD)-XREAL
      VALUE(IMVN+IORD)=VALUE(IMVN+IORD)-XIMAG
      GO TO 10
   20 CONTINUE
C
C      BACK SUBSTITUTION
C
      I=NSTOP
      IORD=NODPLC(IRSWPF+I)
      JORD=NODPLC(ICSWPF+I)
      LOCNN=INDXX(IORD,JORD)
   30 CALL CDIV(VALUE(LVN+IORD),VALUE(IMVN+IORD),VALUE(LYNL+LOCNN),
     1     VALUE(IMYNL+LOCNN),VALUE(LVN+IORD),VALUE(IMVN+IORD))
      I=I-1
      IF (I.LE.1) GO TO 60
      IORD=NODPLC(IRSWPF+I)
      LOC=I
   35 LOC=NODPLC(JCPT+LOC)
   40 IF (NODPLC(JCOLNO+LOC).NE.I) GO TO 35
      LOCNN=LOC
   50 LOC=NODPLC(JCPT+LOC)
      IF (LOC.EQ.0) GO TO 30
      J=NODPLC(JCOLNO+LOC)
      JORD=NODPLC(IRSWPF+J)
      CALL CMULT(VALUE(LYNL+LOC),VALUE(IMYNL+LOC),
     1     VALUE(LVN+JORD),VALUE(IMVN+JORD),XREAL,XIMAG)
      VALUE(LVN+IORD)=VALUE(LVN+IORD)-XREAL
      VALUE(IMVN+IORD)=VALUE(IMVN+IORD)-XIMAG
      GO TO 50
C
C  REORDER SOLUTION VECTOR
C
   60 DO 70 I=1,NSTOP
      J=NODPLC(ICSWPR+I)
      K=NODPLC(IRSWPF+J)
      VALUE(NDIAG+I)=VALUE(LVN+K)
      VALUE(NDIAG+I+NSTOP)=VALUE(IMVN+K)
   70 CONTINUE
      CALL COPY8(VALUE(NDIAG+1),VALUE(LVN+1),NSTOP)
      CALL COPY8(VALUE(NDIAG+1+NSTOP),VALUE(IMVN+1),NSTOP)
      DO 120 I=2,NSTOP
      CVALUE(LCVN+I)=CMPLX(SNGL(VALUE(LVN+I)),SNGL(VALUE(IMVN+I)))
  120 CONTINUE
      CVALUE(LCVN+1)=CMPLX(0.0E0,0.0E0)
C
C  FINISHED
C
      RETURN
      END
      SUBROUTINE ACASOL
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     THIS ROUTINE EVALUATES THE RESPONSE OF THE ADJOINT CIRCUIT BY
C DOING A FORWARD/BACKWARD SUBSTITUTION STEP USING THE TRANSPOSE OF THE
C CIRCUIT EQUATION COEFFICIENT MATRIX.
C
C SPICE VERSION 2G.6  SCCSID=TABINF 3/15/83
      COMMON /TABINF/ IELMNT,ISBCKT,NSBCKT,IUNSAT,NUNSAT,ITEMPS,NUMTEM,
     1   ISENS,NSENS,IFOUR,NFOUR,IFIELD,ICODE,IDELIM,ICOLUM,INSIZE,
     2   JUNODE,LSBKPT,NUMBKP,IORDER,JMNODE,IUR,IUC,ILC,ILR,NUMOFF,ISR,
     3   NMOFFC,ISEQ,ISEQ1,NEQN,NODEVS,NDIAG,ISWAP,IEQUA,MACINS,LVNIM1,
     4   LX0,LVN,LYNL,LYU,LYL,LX1,LX2,LX3,LX4,LX5,LX6,LX7,LD0,LD1,LTD,
     5   IMYNL,IMVN,LCVN,NSNOD,NSMAT,NSVAL,ICNOD,ICMAT,ICVAL,
     6   LOUTPT,LPOL,LZER,IRSWPF,IRSWPR,ICSWPF,ICSWPR,IRPT,JCPT,
     7   IROWNO,JCOLNO,NTTBR,NTTAR,LVNTMP
C SPICE VERSION 2G.6  SCCSID=CIRDAT 3/15/83
      COMMON /CIRDAT/ LOCATE(50),JELCNT(50),NUNODS,NCNODS,NUMNOD,NSTOP,
     1   NUT,NLT,NXTRM,NDIST,NTLIN,IBR,NUMVS,NUMALT,NUMCYC
C SPICE VERSION 2G.6  SCCSID=BLANK 3/15/83
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(64)
      COMPLEX CVALUE(32)
      EQUIVALENCE (VALUE(1),NODPLC(1),CVALUE(1))
C
C  EVALUATES ADJOINT RESPONSE BY DOING FORWARD/BACKWARD SUBSTITUTION ON
C  THE TRANSPOSE OF THE Y MATRIX
C
C  FORWARD SUBSTITUTION
C
      DO 20 I=2,NSTOP
      LOC=I
      IORD=NODPLC(ICSWPF+I)
   10 LOC=NODPLC(IRPT+LOC)
      IF (NODPLC(IROWNO+LOC).GE.I) GO TO 15
      J=NODPLC(IROWNO+LOC)
      JORD=NODPLC(ICSWPF+J)
      CALL CMULT(VALUE(LYNL+LOC),VALUE(IMYNL+LOC),
     1     VALUE(LVN+JORD),VALUE(IMVN+JORD),XREAL,XIMAG)
      VALUE(LVN+IORD)=VALUE(LVN+IORD)-XREAL
      VALUE(IMVN+IORD)=VALUE(IMVN+IORD)-XIMAG
      GO TO 10
   15 JORD=NODPLC(IRSWPF+I)
      LOCNN=INDXX(JORD,IORD)
      CALL CDIV(VALUE(LVN+IORD),VALUE(IMVN+IORD),VALUE(LYNL+LOCNN),
     1     VALUE(IMYNL+LOCNN),VALUE(LVN+IORD),VALUE(IMVN+IORD))
   20 CONTINUE
C
C  BACKWARD SUBSTITUTION
C
      I=NSTOP
   30 I=I-1
      IF (I.LE.1) GO TO 60
      IORD=NODPLC(ICSWPF+I)
      LOC=I
   35 LOC=NODPLC(IRPT+LOC)
   40 IF (NODPLC(IROWNO+LOC).NE.I) GO TO 35
   50 LOC=NODPLC(IRPT+LOC)
      IF (LOC.EQ.0) GO TO 30
      J=NODPLC(IROWNO+LOC)
      JORD=NODPLC(ICSWPF+J)
      CALL CMULT(VALUE(LYNL+LOC),VALUE(IMYNL+LOC),
     1     VALUE(LVN+JORD),VALUE(IMVN+JORD),XREAL,XIMAG)
      VALUE(LVN+IORD)=VALUE(LVN+IORD)-XREAL
      VALUE(IMVN+IORD)=VALUE(IMVN+IORD)-XIMAG
      GO TO 50
C
C  REORDER SOLUTION VECTOR
C
   60 DO 70 I=1,NSTOP
      J=NODPLC(IRSWPR+I)
      K=NODPLC(ICSWPF+J)
      VALUE(NDIAG+I)=VALUE(LVN+K)
      VALUE(NDIAG+I+NSTOP)=VALUE(IMVN+K)
   70 CONTINUE
      CALL COPY8(VALUE(NDIAG+1),VALUE(LVN+1),NSTOP)
      CALL COPY8(VALUE(NDIAG+1+NSTOP),VALUE(IMVN+1),NSTOP)
      DO 120 I=2,NSTOP
      CVALUE(LCVN+I)=CMPLX(SNGL(VALUE(LVN+I)),SNGL(VALUE(IMVN+I)))
  120 CONTINUE
      CVALUE(LCVN+1)=CMPLX(0.0E0,0.0E0)
C
C  FINISHED
C
      RETURN
      END
