C     ERROR-PATH TEST: GETM4 MUST REFUSE A NEGATIVE BLOCK SIZE.
C     EXPECTED TO ABORT WITH "SIZE PARAMETER NEGATIVE" AT ENTRY GETMEM.
      PROGRAM ERRTEST
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /BLANK/ VALUE(200000)
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
      IOFILE=6
      CALL SETMEM(VALUE(1),100000)
      CALL GETM4(IPA,-5)
      STOP
      END
