C     ERROR-PATH TEST: CLRMEM MUST REFUSE A POINTER THAT WAS NEVER
C     RETURNED BY THE MEMORY MANAGER.  EXPECTED TO ABORT WITH
C     "TABLE POINTER INVALID" AT ENTRY CLRMEM.
      PROGRAM ERRTEST
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /BLANK/ VALUE(200000)
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
      IOFILE=6
      CALL SETMEM(VALUE(1),100000)
      IBOGUS=999999
      CALL CLRMEM(IBOGUS)
      STOP
      END
