C     ERROR-PATH TEST: RELMEM MUST REFUSE TO RELEASE MORE WORDS THAN
C     THE BLOCK CURRENTLY HAS IN USE.  EXPECTED TO ABORT WITH
C     "ATTEMPT TO RELEASE MORE THAN TOTAL TABLE" AT ENTRY RELMEM.
      PROGRAM ERRTEST
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /BLANK/ VALUE(200000)
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
      IOFILE=6
      CALL SETMEM(VALUE(1),100000)
      CALL GETM4(IPA,50)
      CALL RELMEM(IPA,200)
      STOP
      END
