C     UNIT TESTS FOR SPICE_ENGINE.F -- PURE NUMERICAL HELPER ROUTINES
C
C     SPICE_ENGINE.F IS MOSTLY A CIRCUIT-SOLUTION STATE MACHINE THAT
C     NEEDS A FULLY-LOADED MATRIX AND DEVICE TABLES TO EXERCISE.  THESE
C     TESTS INSTEAD TARGET THE HANDFUL OF ITS ROUTINES THAT ARE SELF-
C     CONTAINED NUMERICAL UTILITIES -- COMPLEX ARITHMETIC, POLYNOMIAL
C     TERM EVALUATION, AND THE DEVICE VOLTAGE-LIMITING HEURISTICS USED
C     BY THE DIODE/BJT/JFET/MOSFET MODELS TO KEEP NEWTON ITERATION FROM
C     DIVERGING.  RESULTS ARE REPORTED THROUGH CHECK/CHECKEQ, WHICH
C     TALLY PASS/FAIL COUNTS IN COMMON /TESTCNT/.  THE PROGRAM EXITS
C     WITH STATUS 1 IF ANY CHECK FAILED, 0 OTHERWISE, SO IT CAN DRIVE A
C     SHELL TEST RUNNER.
C
      PROGRAM TESTENG
      COMMON /TESTCNT/ NPASS,NFAIL
      NPASS=0
      NFAIL=0
      CALL T01CDIV
      CALL T02CMULT
      CALL T03MAGPHS
      CALL T04EVTERM
      CALL T05NXTPWR
      CALL T06PNJLIM
      CALL T07FETLIM
      CALL T08LIMVDS
      WRITE(6,910) NPASS,NFAIL
  910 FORMAT(/,' TESTS: PASS=',I4,' FAIL=',I4)
      IF (NFAIL.GT.0) CALL EXIT(1)
      CALL EXIT(0)
      END
C
      SUBROUTINE CHECK(OK,LABEL)
      LOGICAL OK
      CHARACTER*(*) LABEL
      COMMON /TESTCNT/ NPASS,NFAIL
      IF (.NOT.OK) GO TO 10
      NPASS=NPASS+1
      WRITE(6,900) LABEL
  900 FORMAT(' PASS: ',A)
      RETURN
   10 NFAIL=NFAIL+1
      WRITE(6,901) LABEL
  901 FORMAT(' FAIL: ',A)
      RETURN
      END
C
C     CHECKEQ -- PASSES WHEN A AND B AGREE TO WITHIN AN ABSOLUTE TOL
C
      SUBROUTINE CHECKEQ(A,B,TOL,LABEL)
      DOUBLE PRECISION A,B,TOL
      CHARACTER*(*) LABEL
      CALL CHECK(DABS(A-B).LE.TOL,LABEL)
      RETURN
      END
C
C     T01 -- CDIV PERFORMS COMPLEX DIVISION, TOLERATES ITS OUTPUT
C            ARGUMENTS BEING ALIASED TO ITS INPUT ARGUMENTS, AND
C            ROUND-TRIPS THROUGH CMULT
C
      SUBROUTINE T01CDIV
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      CALL CDIV(3.0D0,4.0D0,1.0D0,2.0D0,CR,CI)
      CALL CHECKEQ(CR,2.2D0,1.0D-12,
     1   'T01 CDIV real part of (3+4i)/(1+2i)')
      CALL CHECKEQ(CI,-0.4D0,1.0D-12,
     1   'T01 CDIV imag part of (3+4i)/(1+2i)')
C
      CALL CDIV(7.0D0,-5.0D0,2.0D0,3.0D0,QR,QI)
      CALL CMULT(QR,QI,2.0D0,3.0D0,RR,RI)
      CALL CHECKEQ(RR,7.0D0,1.0D-9,'T01 (X/Y)*Y real part round-trips')
      CALL CHECKEQ(RI,-5.0D0,1.0D-9,'T01 (X/Y)*Y imag part round-trips')
C
      XR=9.0D0
      XI=6.0D0
      CALL CDIV(XR,XI,3.0D0,0.0D0,XR,XI)
      CALL CHECKEQ(XR,3.0D0,1.0D-12,
     1   'T01 CDIV writes back through an aliased real output')
      CALL CHECKEQ(XI,2.0D0,1.0D-12,
     1   'T01 CDIV writes back through an aliased imag output')
      RETURN
      END
C
C     T02 -- CMULT PERFORMS COMPLEX MULTIPLICATION
C
      SUBROUTINE T02CMULT
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      CALL CMULT(3.0D0,4.0D0,1.0D0,2.0D0,CR,CI)
      CALL CHECKEQ(CR,-5.0D0,1.0D-12,
     1   'T02 CMULT real part of (3+4i)*(1+2i)')
      CALL CHECKEQ(CI,10.0D0,1.0D-12,
     1   'T02 CMULT imag part of (3+4i)*(1+2i)')
C
C     MULTIPLYING A COMPLEX NUMBER BY ITS OWN CONJUGATE GIVES A REAL
C     RESULT EQUAL TO ITS MAGNITUDE SQUARED
C
      CALL CMULT(5.0D0,-2.0D0,5.0D0,2.0D0,CR2,CI2)
      CALL CHECKEQ(CR2,29.0D0,1.0D-12,
     1   'T02 CMULT by conjugate gives magnitude squared')
      CALL CHECKEQ(CI2,0.0D0,1.0D-12,
     1   'T02 CMULT by conjugate cancels the imaginary part')
      RETURN
      END
C
C     T03 -- MAGPHS COMPUTES MAGNITUDE AND PHASE (IN DEGREES) OF A
C            COMPLEX NUMBER, AND CLAMPS RATHER THAN DIVIDING BY ZERO
C            WHEN THE INPUT VANISHES
C
      SUBROUTINE T03MAGPHS
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /KNSTNT/ TWOPI,XLOG2,XLOG10,ROOT2,RAD,BOLTZ,CHARGE,CTOK,
     1   GMIN,RELTOL,ABSTOL,VNTOL,TRTOL,CHGTOL,EPS0,EPSSIL,EPSOX,
     2   PIVTOL,PIVREL
      COMPLEX CVAR
      TWOPI=8.0D0*DATAN2(1.0D0,1.0D0)
      RAD=360.0D0/TWOPI
C
      CVAR=CMPLX(3.0,4.0)
      CALL MAGPHS(CVAR,XMAG,XPHS)
      CALL CHECKEQ(XMAG,5.0D0,1.0D-6,'T03 MAGPHS magnitude of 3+4i')
      CALL CHECKEQ(XPHS,53.13010235D0,1.0D-4,
     1   'T03 MAGPHS phase of 3+4i in degrees')
C
      CVAR=CMPLX(0.0,0.0)
      CALL MAGPHS(CVAR,XMAG,XPHS)
      CALL CHECK(XMAG.EQ.1.0D-20,
     1   'T03 MAGPHS clamps a zero vector to a nonzero magnitude')
      CALL CHECK(XPHS.EQ.0.0D0,
     1   'T03 MAGPHS reports zero phase for a clamped vector')
      RETURN
      END
C
C     T04 -- EVTERM RAISES A NUMBER TO AN INTEGER POWER, USING DIRECT
C            MULTIPLICATION FOR SMALL EXPONENTS (0..4) AND A LOG/EXP
C            IDENTITY -- WITH EXPLICIT SIGN RESTORATION -- FOR LARGER
C            ONES
C
      SUBROUTINE T04EVTERM
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      CALL EVTERM(VAL,7.0D0,0)
      CALL CHECKEQ(VAL,1.0D0,1.0D-12,'T04 EVTERM x^0 is 1')
      CALL EVTERM(VAL,7.0D0,1)
      CALL CHECKEQ(VAL,7.0D0,1.0D-12,'T04 EVTERM x^1 is x')
      CALL EVTERM(VAL,3.0D0,2)
      CALL CHECKEQ(VAL,9.0D0,1.0D-12,'T04 EVTERM x^2')
      CALL EVTERM(VAL,3.0D0,3)
      CALL CHECKEQ(VAL,27.0D0,1.0D-12,'T04 EVTERM x^3')
      CALL EVTERM(VAL,3.0D0,4)
      CALL CHECKEQ(VAL,81.0D0,1.0D-9,'T04 EVTERM x^4')
C
      CALL EVTERM(VAL,2.0D0,5)
      CALL CHECKEQ(VAL,32.0D0,1.0D-9,'T04 EVTERM 2^5 via log/exp path')
      CALL EVTERM(VAL,-2.0D0,5)
      CALL CHECKEQ(VAL,-32.0D0,1.0D-9,
     1   'T04 EVTERM (-2)^5 keeps a negative sign for odd exponents')
      CALL EVTERM(VAL,-2.0D0,6)
      CALL CHECKEQ(VAL,64.0D0,1.0D-9,
     1   'T04 EVTERM (-2)^6 is positive for even exponents')
C
      CALL EVTERM(VAL,0.0D0,5)
      CALL CHECK(VAL.EQ.0.0D0,
     1   'T04 EVTERM zero base short-circuits to avoid LOG(0)')
      RETURN
      END
C
C     T05 -- NXTPWR ENUMERATES THE EXPONENT TUPLES OF A MULTI-VARIABLE
C            POLYNOMIAL IN ORDER OF NONDECREASING TOTAL DEGREE.  FOR TWO
C            VARIABLES, STARTING FROM (0,0), THE KNOWN SEQUENCE IS
C            (1,0) (0,1) (2,0) (1,1) (0,2) ...
C
      SUBROUTINE T05NXTPWR
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL OK
      INTEGER PWR(2)
      PWR(1)=0
      PWR(2)=0
      CALL NXTPWR(PWR,2)
      CALL CHECK(PWR(1).EQ.1.AND.PWR(2).EQ.0,
     1   'T05 NXTPWR term after (0,0) is (1,0)')
      CALL NXTPWR(PWR,2)
      CALL CHECK(PWR(1).EQ.0.AND.PWR(2).EQ.1,
     1   'T05 NXTPWR next term is (0,1)')
      CALL NXTPWR(PWR,2)
      CALL CHECK(PWR(1).EQ.2.AND.PWR(2).EQ.0,
     1   'T05 NXTPWR next term is (2,0)')
      CALL NXTPWR(PWR,2)
      CALL CHECK(PWR(1).EQ.1.AND.PWR(2).EQ.1,
     1   'T05 NXTPWR next term is (1,1)')
      CALL NXTPWR(PWR,2)
      CALL CHECK(PWR(1).EQ.0.AND.PWR(2).EQ.2,
     1   'T05 NXTPWR next term is (0,2)')
C
C     REGARDLESS OF THE EXACT ORDERING WITHIN A DEGREE, THE TOTAL DEGREE
C     OF SUCCESSIVE TERMS MUST NEVER GO BACKWARDS
C
      PWR(1)=0
      PWR(2)=0
      IDEGPR=0
      OK=.TRUE.
      DO 10 K=1,20
        CALL NXTPWR(PWR,2)
        IDEG=PWR(1)+PWR(2)
        IF (IDEG.LT.IDEGPR) OK=.FALSE.
        IDEGPR=IDEG
   10 CONTINUE
      CALL CHECK(OK,'T05 NXTPWR total degree is non-decreasing')
      RETURN
      END
C
C     T06 -- PNJLIM CLAMPS THE PER-ITERATION CHANGE OF A PN-JUNCTION
C            VOLTAGE.  IT IS A NO-OP CLOSE TO THE OPERATING POINT, LOG-
C            LIMITS LARGE FORWARD STEPS, AND FALLS BACK TO A LOG-OF-
C            RATIO OR AN OUTRIGHT CLAMP TO VCRIT IN THE REMAINING CASES.
C
      SUBROUTINE T06PNJLIM
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      VT=0.025852D0
C
C     BELOW VCRIT: NO LIMITING, AND ICHECK IS EXPLICITLY CLEARED
C
      ICHECK=1
      VNEW=0.4D0
      CALL PNJLIM(VNEW,0.3D0,VT,0.6D0,ICHECK)
      CALL CHECKEQ(VNEW,0.4D0,1.0D-12,
     1   'T06 PNJLIM leaves VNEW alone below VCRIT')
      CALL CHECK(ICHECK.EQ.0,'T06 PNJLIM clears ICHECK below VCRIT')
C
C     ABOVE VCRIT BUT WITHIN 2*VT OF VOLD: STILL A NO-OP
C
      ICHECK=1
      VNEW=0.62D0
      CALL PNJLIM(VNEW,0.6D0,VT,0.5D0,ICHECK)
      CALL CHECKEQ(VNEW,0.62D0,1.0D-12,
     1   'T06 PNJLIM leaves VNEW alone within 2*VT of VOLD')
      CALL CHECK(ICHECK.EQ.0,
     1   'T06 PNJLIM clears ICHECK within 2*VT of VOLD')
C
C     A LARGE FORWARD STEP FROM A POSITIVE VOLD IS LOG-LIMITED, AND
C     ICHECK IS LEFT UNTOUCHED SO THE CALLER KNOWS TO RE-ITERATE
C
      ICHECK=1
      VNEW=0.9D0
      CALL PNJLIM(VNEW,0.6D0,VT,0.5D0,ICHECK)
      CALL CHECKEQ(VNEW,0.6D0+VT*DLOG(1.0D0+0.3D0/VT),1.0D-9,
     1   'T06 PNJLIM log-limits a large forward step')
      CALL CHECK(ICHECK.EQ.1,
     1   'T06 PNJLIM leaves ICHECK untouched once limiting kicks in')
C
C     A STEP THAT WOULD DRIVE THE LOG ARGUMENT NEGATIVE CLAMPS TO VCRIT
C     OUTRIGHT
C
      VNEW=-1.0D0
      CALL PNJLIM(VNEW,1.0D0,VT,-2.0D0,ICHECK)
      CALL CHECKEQ(VNEW,-2.0D0,1.0D-12,
     1   'T06 PNJLIM clamps to VCRIT when log argument goes negative')
C
C     A NON-POSITIVE VOLD ROUTES THROUGH THE LOG-OF-RATIO BRANCH
C
      VNEW=0.8D0
      CALL PNJLIM(VNEW,-0.1D0,VT,0.5D0,ICHECK)
      CALL CHECKEQ(VNEW,VT*DLOG(0.8D0/VT),1.0D-9,
     1   'T06 PNJLIM uses log-of-ratio branch for non-positive VOLD')
      RETURN
      END
C
C     T07 -- FETLIM CLAMPS THE PER-ITERATION CHANGE OF A FET GATE
C            VOLTAGE DIFFERENTLY DEPENDING ON WHETHER VOLD PLACES THE
C            DEVICE DEFINITELY OFF, IN THE TRANSITION BAND, OR
C            DEFINITELY ON
C
      SUBROUTINE T07FETLIM
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      VTO=1.0D0
C
C     DEFINITELY OFF: VOLD.LT.VTO  (HERE VOLD=0.0)
C
      VNEW=2.0D0
      CALL FETLIM(VNEW,0.0D0,VTO)
      CALL CHECKEQ(VNEW,1.5D0,1.0D-12,
     1   'T07 FETLIM (off) clamps a large upward step to VTO+0.5')
      VNEW=1.2D0
      CALL FETLIM(VNEW,0.0D0,VTO)
      CALL CHECKEQ(VNEW,1.2D0,1.0D-12,
     1   'T07 FETLIM (off) leaves a small upward step alone')
      VNEW=-1.0D0
      CALL FETLIM(VNEW,0.0D0,VTO)
      CALL CHECKEQ(VNEW,-1.0D0,1.0D-12,
     1   'T07 FETLIM (off) leaves a small downward step alone')
      VNEW=-10.0D0
      CALL FETLIM(VNEW,0.0D0,VTO)
      CALL CHECKEQ(VNEW,-4.0D0,1.0D-12,
     1   'T07 FETLIM (off) clamps a large downward step')
C
C     TRANSITION BAND: VTO.LE.VOLD.LT.VTO+3.5  (HERE VOLD=2.0)
C
      VNEW=10.0D0
      CALL FETLIM(VNEW,2.0D0,VTO)
      CALL CHECKEQ(VNEW,5.0D0,1.0D-12,
     1   'T07 FETLIM (transition) clamps an upward step to VTO+4')
      VNEW=3.0D0
      CALL FETLIM(VNEW,2.0D0,VTO)
      CALL CHECKEQ(VNEW,3.0D0,1.0D-12,
     1   'T07 FETLIM (transition) leaves a small upward step alone')
      VNEW=-5.0D0
      CALL FETLIM(VNEW,2.0D0,VTO)
      CALL CHECKEQ(VNEW,0.5D0,1.0D-12,
     1   'T07 FETLIM (transition) clamps a downward step to VTO-0.5')
      VNEW=1.5D0
      CALL FETLIM(VNEW,2.0D0,VTO)
      CALL CHECKEQ(VNEW,1.5D0,1.0D-12,
     1   'T07 FETLIM (transition) leaves a small downward step alone')
C
C     DEFINITELY ON: VOLD.GE.VTO+3.5  (HERE VOLD=5.0)
C
      VNEW=8.0D0
      CALL FETLIM(VNEW,5.0D0,VTO)
      CALL CHECKEQ(VNEW,8.0D0,1.0D-12,
     1   'T07 FETLIM (on) leaves a small upward step alone')
      VNEW=20.0D0
      CALL FETLIM(VNEW,5.0D0,VTO)
      CALL CHECKEQ(VNEW,15.0D0,1.0D-12,
     1   'T07 FETLIM (on) clamps a large upward step')
      VNEW=4.6D0
      CALL FETLIM(VNEW,5.0D0,VTO)
      CALL CHECKEQ(VNEW,4.6D0,1.0D-12,
     1   'T07 FETLIM (on) leaves a small downward step alone')
      VNEW=1.0D0
      CALL FETLIM(VNEW,5.0D0,VTO)
      CALL CHECKEQ(VNEW,3.0D0,1.0D-12,
     1   'T07 FETLIM (on) clamps a downward step that crosses VTOX')
      RETURN
      END
C
C     T08 -- LIMVDS CLAMPS THE PER-ITERATION CHANGE OF A FET DRAIN-
C            SOURCE VOLTAGE, WITH DIFFERENT LIMITS DEPENDING ON WHETHER
C            VOLD IS ABOVE OR BELOW 3.5V
C
      SUBROUTINE T08LIMVDS
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      VNEW=5.0D0
      CALL LIMVDS(VNEW,2.0D0)
      CALL CHECKEQ(VNEW,4.0D0,1.0D-12,
     1   'T08 LIMVDS (VOLD<3.5) clamps a large upward step to 4')
      VNEW=-2.0D0
      CALL LIMVDS(VNEW,2.0D0)
      CALL CHECKEQ(VNEW,-0.5D0,1.0D-12,
     1   'T08 LIMVDS (VOLD<3.5) clamps a downward step to -0.5')
      VNEW=20.0D0
      CALL LIMVDS(VNEW,4.0D0)
      CALL CHECKEQ(VNEW,14.0D0,1.0D-12,
     1   'T08 LIMVDS (VOLD>=3.5) clamps an upward step to 3*VOLD+2')
      VNEW=1.0D0
      CALL LIMVDS(VNEW,4.0D0)
      CALL CHECKEQ(VNEW,2.0D0,1.0D-12,
     1   'T08 LIMVDS (VOLD>=3.5) clamps a step that drops below 3.5')
      VNEW=4.0D0
      CALL LIMVDS(VNEW,5.0D0)
      CALL CHECKEQ(VNEW,4.0D0,1.0D-12,
     1   'T08 LIMVDS (VOLD>=3.5) leaves a step above 3.5 alone')
      RETURN
      END
