C     UNIT TESTS FOR SPICE_MEMMGR.F -- THE DYNAMIC MEMORY MANAGER
C
C     EACH TEST SUBROUTINE CALLS SETMEM ITSELF, SO TESTS ARE
C     INDEPENDENT OF ONE ANOTHER (A FRESH SETMEM DISCARDS ALL PRIOR
C     BLOCK-TABLE STATE).  RESULTS ARE REPORTED THROUGH CHECK, WHICH
C     TALLIES PASS/FAIL COUNTS IN COMMON /TESTCNT/.  THE PROGRAM EXITS
C     WITH STATUS 1 IF ANY CHECK FAILED, 0 OTHERWISE, SO IT CAN DRIVE
C     A SHELL TEST RUNNER.
C
      PROGRAM TESTMM
      COMMON /TESTCNT/ NPASS,NFAIL
      NPASS=0
      NFAIL=0
      CALL T01ALLOC
      CALL T02ISOLATE
      CALL T03RELMEM
      CALL T04EXTMEM
      CALL T05EXTGROW
      CALL T06CLRMEM
      CALL T07CRUNCH
      CALL T08PTRMEM
      CALL T09SLPMEM
      CALL T10AVLM
      CALL T11ZEROSZ
      WRITE(6,910) NPASS,NFAIL
  910 FORMAT(/,' TESTS: PASS=',I4,' FAIL=',I4)
      IF (NFAIL.GT.0) CALL EXIT(1)
      CALL EXIT(0)
      END
C
      SUBROUTINE CHECK(OK,LABEL)
      LOGICAL OK
      CHARACTER*(*) LABEL
      COMMON /TESTCNT/ NPASS,NFAIL
      IF (.NOT.OK) GO TO 10
      NPASS=NPASS+1
      WRITE(6,900) LABEL
  900 FORMAT(' PASS: ',A)
      RETURN
   10 NFAIL=NFAIL+1
      WRITE(6,901) LABEL
  901 FORMAT(' FAIL: ',A)
      RETURN
      END
C
C     T01 -- GETM4 ALLOCATES A BLOCK WHOSE SIZE AND CONTENTS ROUND-TRIP
C
      SUBROUTINE T01ALLOC
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL OK
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(200000)
      EQUIVALENCE (VALUE(1),NODPLC(1))
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
      IOFILE=6
      CALL SETMEM(VALUE(1),100000)
      CALL GETM4(IPA,50)
      DO 10 K=1,50
        NODPLC(IPA+K)=1000+K
   10 CONTINUE
      CALL SIZMEM(IPA,ISZ)
      CALL CHECK(ISZ.EQ.50,'T01 SIZMEM reports requested size')
      OK=.TRUE.
      DO 20 K=1,50
        IF (NODPLC(IPA+K).NE.1000+K) OK=.FALSE.
   20 CONTINUE
      CALL CHECK(OK,'T01 written pattern reads back unchanged')
      RETURN
      END
C
C     T02 -- THREE SIMULTANEOUS BLOCKS DO NOT OVERLAP OR CORRUPT
C            EACH OTHER'S DATA
C
      SUBROUTINE T02ISOLATE
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL OK
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(200000)
      EQUIVALENCE (VALUE(1),NODPLC(1))
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
      IOFILE=6
      CALL SETMEM(VALUE(1),100000)
      CALL GETM4(IPA,50)
      CALL GETM4(IPB,50)
      CALL GETM4(IPC,50)
      CALL CHECK(IPA.NE.IPB.AND.IPB.NE.IPC.AND.IPA.NE.IPC,
     1   'T02 three blocks get distinct pointers')
      DO 10 K=1,50
        NODPLC(IPA+K)=1000+K
        NODPLC(IPB+K)=2000+K
        NODPLC(IPC+K)=3000+K
   10 CONTINUE
      OK=.TRUE.
      DO 20 K=1,50
        IF (NODPLC(IPA+K).NE.1000+K) OK=.FALSE.
        IF (NODPLC(IPB+K).NE.2000+K) OK=.FALSE.
        IF (NODPLC(IPC+K).NE.3000+K) OK=.FALSE.
   20 CONTINUE
      CALL CHECK(OK,'T02 three interleaved patterns stay isolated')
      RETURN
      END
C
C     T03 -- RELMEM SHRINKS A BLOCK AND RETURNS EXACTLY THE EXPECTED
C            NUMBER OF WORDS TO THE FREE POOL, WITHOUT DISTURBING THE
C            SURVIVING (RETAINED) CONTENTS
C
      SUBROUTINE T03RELMEM
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL OK
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(200000)
      EQUIVALENCE (VALUE(1),NODPLC(1))
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
      NEV(N)=((N+3)/4)*4
      IOFILE=6
      CALL SETMEM(VALUE(1),100000)
      CALL GETM4(IPA,50)
      DO 10 K=1,50
        NODPLC(IPA+K)=1000+K
   10 CONTINUE
      CALL AVLM4(IAVL0)
      CALL RELMEM(IPA,20)
      CALL SIZMEM(IPA,ISZ)
      CALL CHECK(ISZ.EQ.30,'T03 SIZMEM reflects release of 20/50')
      CALL AVLM4(IAVL1)
      CALL CHECK(IAVL1-IAVL0.EQ.NEV(50)-NEV(30),
     1   'T03 released words returned to free pool')
      OK=.TRUE.
      DO 20 K=1,30
        IF (NODPLC(IPA+K).NE.1000+K) OK=.FALSE.
   20 CONTINUE
      CALL CHECK(OK,'T03 retained 30 words keep original contents')
      RETURN
      END
C
C     T04 -- EXTMEM GROWS A BLOCK BACK IN PLACE WHEN ROOM IS AVAILABLE
C            ABOVE IT, PRESERVING THE ORIGINAL DATA
C
      SUBROUTINE T04EXTMEM
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL OK
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(200000)
      EQUIVALENCE (VALUE(1),NODPLC(1))
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
      IOFILE=6
      CALL SETMEM(VALUE(1),100000)
      CALL GETM4(IPA,50)
      DO 10 K=1,50
        NODPLC(IPA+K)=1000+K
   10 CONTINUE
      CALL RELMEM(IPA,20)
      IPSAVE=IPA
      CALL EXTMEM(IPA,10)
      CALL SIZMEM(IPA,ISZ)
      CALL CHECK(ISZ.EQ.40,'T04 SIZMEM reflects shrink then grow')
      CALL CHECK(IPA.EQ.IPSAVE,
     1   'T04 in-place extend keeps same pointer')
      OK=.TRUE.
      DO 20 K=1,30
        IF (NODPLC(IPA+K).NE.1000+K) OK=.FALSE.
   20 CONTINUE
      CALL CHECK(OK,'T04 original 30 words survive the extend')
      NODPLC(IPA+40)=9999
      CALL CHECK(NODPLC(IPA+40).EQ.9999,
     1   'T04 newly extended words are writable')
      RETURN
      END
C
C     T05 -- EXTMEM CAN FORCE THE MANAGER TO GROW ITS TOTAL ARENA
C            (ICORE) WHEN THE REQUEST EXCEEDS CURRENTLY RESERVED SPACE,
C            AND EXISTING DATA SURVIVES THE GROWTH
C
      SUBROUTINE T05EXTGROW
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL OK
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(200000)
      EQUIVALENCE (VALUE(1),NODPLC(1))
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
      IOFILE=6
      CALL SETMEM(VALUE(1),100000)
      ICORE0=ICORE
      CALL GETM4(IPA,50)
      DO 10 K=1,50
        NODPLC(IPA+K)=1000+K
   10 CONTINUE
      CALL EXTMEM(IPA,3000)
      CALL CHECK(MEMERR.EQ.0,'T05 large extend reports no error')
      CALL CHECK(ICORE.GT.ICORE0,'T05 arena grows to satisfy request')
      CALL SIZMEM(IPA,ISZ)
      CALL CHECK(ISZ.EQ.3050,'T05 SIZMEM reflects grown size')
      OK=.TRUE.
      DO 20 K=1,50
        IF (NODPLC(IPA+K).NE.1000+K) OK=.FALSE.
   20 CONTINUE
      CALL CHECK(OK,'T05 original data survives arena growth')
      RETURN
      END
C
C     T06 -- CLRMEM INVALIDATES THE POINTER AND RETURNS THE BLOCK'S
C            SPACE (PLUS ITS TABLE ENTRY) TO THE FREE POOL, WITHOUT
C            TOUCHING OTHER LIVE BLOCKS
C
      SUBROUTINE T06CLRMEM
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL OK
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(200000)
      EQUIVALENCE (VALUE(1),NODPLC(1))
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
      NEV(N)=((N+3)/4)*4
      IOFILE=6
      CALL SETMEM(VALUE(1),100000)
      CALL GETM4(IPA,30)
      CALL GETM4(IPB,30)
      DO 10 K=1,30
        NODPLC(IPA+K)=1000+K
        NODPLC(IPB+K)=2000+K
   10 CONTINUE
      CALL AVLM4(IAVL0)
      CALL CLRMEM(IPB)
      CALL CHECK(IPB.EQ.2**30-1,
     1   'T06 cleared pointer set to sentinel 2**30-1')
      CALL AVLM4(IAVL1)
      CALL CHECK(IAVL1-IAVL0.EQ.NEV(30)+NTAB,
     1   'T06 cleared block and its table slot are freed')
      OK=.TRUE.
      DO 20 K=1,30
        IF (NODPLC(IPA+K).NE.1000+K) OK=.FALSE.
   20 CONTINUE
      CALL CHECK(OK,'T06 surviving block is untouched by CLRMEM')
      RETURN
      END
C
C     T07 -- CRUNCH COMPACTS FREED HOLES AND AUTOMATICALLY UPDATES A
C            SURVIVING BLOCK'S OWN POINTER VARIABLE TO ITS NEW ADDRESS
C            (NO PTRMEM NEEDED FOR THE POINTER GETM4 WAS GIVEN)
C
      SUBROUTINE T07CRUNCH
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL OK
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(200000)
      EQUIVALENCE (VALUE(1),NODPLC(1))
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
      IOFILE=6
      CALL SETMEM(VALUE(1),100000)
      CALL GETM4(IPA,30)
      CALL GETM4(IPB,30)
      CALL GETM4(IPC,30)
      DO 10 K=1,30
        NODPLC(IPA+K)=1000+K
        NODPLC(IPB+K)=2000+K
        NODPLC(IPC+K)=3000+K
   10 CONTINUE
      IPCBEFORE=IPC
      CALL CLRMEM(IPA)
      CALL CRUNCH
      CALL CHECK(IPC.NE.IPCBEFORE,
     1   'T07 CRUNCH relocates a block after a hole opens below it')
      OK=.TRUE.
      DO 20 K=1,30
        IF (NODPLC(IPC+K).NE.3000+K) OK=.FALSE.
        IF (NODPLC(IPB+K).NE.2000+K) OK=.FALSE.
   20 CONTINUE
      CALL CHECK(OK,
     1   'T07 data intact for both blocks after compaction')
      RETURN
      END
C
C     T08 -- PTRMEM HANDS TRACKING OF A BLOCK OFF FROM ONE VARIABLE TO
C            ANOTHER: ONLY THE NEWLY REGISTERED VARIABLE IS KEPT
C            CURRENT WHEN A LATER CRUNCH RELOCATES THE BLOCK
C
      SUBROUTINE T08PTRMEM
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL OK
      COMMON /BLANK/ VALUE(200000)
      INTEGER NODPLC(200000)
      EQUIVALENCE (VALUE(1),NODPLC(1))
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
      IOFILE=6
      CALL SETMEM(VALUE(1),100000)
      CALL GETM4(IPA,30)
      CALL GETM4(IPD,30)
      DO 10 K=1,30
        NODPLC(IPD+K)=4000+K
   10 CONTINUE
      IPE=IPD
      CALL PTRMEM(IPD,IPE)
      IPD=-999
      CALL GETM4(IPF,10)
      CALL CLRMEM(IPA)
      CALL CRUNCH
      OK=.TRUE.
      DO 20 K=1,30
        IF (NODPLC(IPE+K).NE.4000+K) OK=.FALSE.
   20 CONTINUE
      CALL CHECK(OK,
     1   'T08 handed-off pointer tracks block through CRUNCH')
      RETURN
      END
C
C     T09 -- SLPMEM RESERVES SLOP SO THAT A SUBSEQUENT EXTMEM WITHIN
C            THAT MARGIN GROWS THE BLOCK WITHOUT RELOCATING THE BLOCK
C            TABLE (NO INCREASE IN THE CPYKNT COPY COUNTER)
C
      SUBROUTINE T09SLPMEM
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL OK
      COMMON /BLANK/ VALUE(200000)
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      COMMON /FLAGS/ IPRNTA,IPRNTL,IPRNTM,IPRNTN,IPRNTO,LIMTIM,LIMPTS,
     1   LVLCOD,LVLTIM,ITL1,ITL2,ITL3,ITL4,ITL5,ITL6,IGOOF,NOGO,KEOF
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
      IOFILE=6
      CALL SETMEM(VALUE(1),100000)
      CALL GETM4(IPG,10)
      CALL SLPMEM(IPG,20)
      CPY0=CPYKNT
      CALL EXTMEM(IPG,5)
      CPY1=CPYKNT
      CALL CHECK(CPY1.EQ.CPY0,
     1   'T09 extend within reserved slop copies nothing')
      RETURN
      END
C
C     T10 -- AVLM4/AVLM8/AVLM16 ALL MEASURE THE SAME UNDERLYING FREE
C            BYTE SPACE, JUST IN DIFFERENT WORD-SIZE UNITS: MULTIPLYING
C            EACH REPORTED COUNT BY ITS OWN STRIDE MUST AGREE
C
      SUBROUTINE T10AVLM
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /BLANK/ VALUE(200000)
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
      IOFILE=6
      CALL SETMEM(VALUE(1),100000)
      CALL AVLM4(IA4)
      CALL AVLM8(IA8)
      CALL AVLM16(IA16)
      CALL CHECK(IA4*NWD4.EQ.IA8*NWD8.AND.IA8*NWD8.EQ.IA16*NWD16,
     1   'T10 AVLM4/8/16 agree on the same free byte space')
      RETURN
      END
C
C     T11 -- A ZERO-SIZE BLOCK IS A LEGAL EDGE CASE: IT ALLOCATES
C            CLEANLY AND REPORTS SIZE ZERO
C
      SUBROUTINE T11ZEROSZ
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /BLANK/ VALUE(200000)
      COMMON /MEMMGR/ CPYKNT,ISTACK(1),LORG,ICORE,MAXCOR,MAXUSE,MEMAVL,
     1   LDVAL,NUMBLK,LOCTAB,LTAB,IFWA,NWOFF,NTAB,MAXMEM,MEMERR,NWD4,
     2   NWD8,NWD16
      COMMON /STATUS/ OMEGA,TIME,DELTA,DELOLD(7),AG(7),VT,XNI,EGFET,
     1   XMU,SFACTR,MODE,MODEDC,ICALC,INITF,METHOD,IORD,MAXORD,NONCON,
     2   ITERNO,ITEMNO,NOSOLV,MODAC,IPIV,IVMFLG,IPOSTP,ISCRCH,IOFILE
      IOFILE=6
      CALL SETMEM(VALUE(1),100000)
      CALL GETM4(IPZ,0)
      CALL CHECK(MEMERR.EQ.0,'T11 zero-size GETM4 reports no error')
      CALL SIZMEM(IPZ,ISZ)
      CALL CHECK(ISZ.EQ.0,'T11 zero-size block reports SIZMEM=0')
      RETURN
      END
